{
  "hash": "1de64e9b6a6a921dd02924beb879ad2d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Gute Vergleiche: Vergleichsgegenstände -- Akt I\"\nslide-level: 2   # <— hier trennt Quarto an \"##\"\nlightbox: true\ncss: global.css\nformat: \n  revealjs:\n    fig-format: svg\n    fig-width: 12\n    fig-asp: 0.618\n    out-width: \"70%\"\n    fig-align: center\n    width: 1280\n    height: 800\n    auto-stretch: false\n    theme: style.scss\n    margin: 0.05\n    slideNumber: true\n    mermaid: \n      theme: neutral\n      look: classic\n      layout: elk\neditor: source\ntbl-cap-location: bottom\nexecute: \n  echo: false\n  message: false\n  warning: false\n---\n\n## Worauf hin wir vergleichen, ist bedeutsam!\n\n![Sprachkompetenz und Bildungshintergrund der Eltern [(Link zur Studie)](https://www.diw.de/de/diw_01.c.619383.de/publikationen/wochenberichte/2019_16/sprachkompetenz_von_kindern__unterschied_nach_bildung_der_eltern_im_unteren_leistungsbereich_besonders_gross.html)](./images/sprachkompetenz.png)\n\n## Beschreiben von Verteilungen (=deskriptive Statistik)\n\nNachdem wir operationalisiert und Daten für die theoretischen Konstrukte erhoben haben, liegen die Daten nun in einer Datenmatrix vor.\n\nDiese Datenmatrix ist meist in ihrer Gesamtheit uninformativ, denn einzelne Werte sagen uns nichts über die **Typik** von Eigenschaften oder über **Zusammenhänge** zwischen Eigenschaften etwas aus.\n\nUm Daten gut zu beschreiben, müssen wir sie sinnvoll zusammenfassen (= aggregieren). Dies ist Aufgabe der *deskriptiven Statistik*.\n\n## Ein Schritt zurück: Was heißt es \"Daten\" sinnvoll zu aggregieren? {.midi}\n\nEine Verteilung der Werte einer Eigenschaft $Y$ gibt an, wie *häufig* diese Werte innerhalb einer (analytischen) Stichprobe vorkommen. Diese Häufigkeit kann in unterschiedlicher Weise angegeben werden:\n\nDiese Häufigkeiten werden auf der Y-Achse (der vertikalen Dimension) grafisch abgetragen. Auf der X-Achse (horizontale Dimension) werden die Ausprägungen abgetragen. Je nach Skalenniveau der gemessenen Eigenschaften sind dies daher Kategorien, Ränge oder Werte in gleichen Intervallen.\n\n## Absolute Häufigkeiten\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](16-VergleichsgegenstaendeI_files/figure-revealjs/unnamed-chunk-1-1.svg)\n:::\n:::\n\n\n## Relative Häufigkeiten\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](16-VergleichsgegenstaendeI_files/figure-revealjs/unnamed-chunk-2-1.svg)\n:::\n:::\n\n\n## Differenzen Jung (\\<40) vs. \"Alt\" (\\>=40)\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](16-VergleichsgegenstaendeI_files/figure-revealjs/unnamed-chunk-3-1.svg)\n:::\n:::\n\n\n## Balken und Dichteverteilungen\n\n<iframe width=\"100%\" height=\"100%\" src=\"https://019d8bab-fc3c-3183-4e72-e68823568837.share.connect.posit.cloud\">\n\n</iframe>\n\n## Häufigkeiten: Notation & Begriffe {.midi style=\"font-size: 80%\"}\n\n+------------------------+-----------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Notation               | Bedeutung                   | Beispiel                                                                                                                                                                                    |\n+:=======================+:============================+:============================================================================================================================================================================================+\n| $N$                    | Absolute Häufigkeit         | 4.850 Personen gaben in der Stichprobe von 2018 an, 40h arbeiten zu wollen.                                                                                                                 |\n+------------------------+-----------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| $P(y)$                 | Wahrscheinlichkeit          | Mit einer Wahrscheinlichkeit von 0.2872 ziehen wir aus der Stichprobe eine Person, die genau 40h als gewünschte Arbeitszeit angegeben hat.                                                  |\n+------------------------+-----------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| $P(y)\\cdot 100$        | relative Häufigkeit         | 28.72% der Befragten gaben an, 40h arbeiten zu wollen.                                                                                                                                      |\n+------------------------+-----------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| $P(y) \\, | \\, (X = x)$ | Bedingte Wahrscheinlichkeit | Unter der Bedingung, dass wir nur Männer analysieren, ist die Wahrscheinlichkeit, einen Befragten zu ziehen, der 40h arbeiten will, 0.4. Bei Frauen liegt diese Wahrscheinlichkeit bei 0.17 |\n+------------------------+-----------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n\n## Relative Häufigkeiten drücken Relationen aus! {.midi}\n\nWahrscheinlichkeiten oder *relative* Häufigkeiten haben immer eine Bedeutung in Relation zum Nenner. Wenn sich der Nenner ändert, ändert sich auch die Bedeutung der relativen Häufigkeit. Klären Sie daher stets, auf welche *Basis* die relativen Häufigkeiten beziehen. Wir können folgende Relationen grob unterscheiden:\n\n-   Relation zur Stichprobengröße\n\n-   Relation zu einer bestimmten Gruppe definiert durch Ausprägungen in X\n\n-   Relation zu einer bestimmten Gruppe definiert durch Ausprägungen in Y\n\nDie erste Variante wird typischerweise als \"Zellenprozent\", die zweite als \"Zeilenprozent\" und die dritte als \"Spaltenprozent\" bezeichnet.\n\n## Armutsrisiko (Zeilenprozent)\n\nWie hoch ist die Wahrscheinlichkeit einen Haushalt in Armut zu finden *innerhalb* eines bestimmten Haushaltstyps?\n\n``` {fontsize=\"\\\\small\"}\nErwerbskonstella |  Armutsgef. Haushalt\n            tion |      nein         ja |     Total\n-----------------+----------------------+----------\n         Rentner |     84.74      15.26 |    100.00 \n      Joblose HH |     33.51      66.49 |    100.00 \n Doppelverdiener |     99.61       0.39 |    100.00 \n Alleinverdiener |     91.42       8.58 |    100.00 \n     Zuverdiener |     97.68       2.32 |    100.00 \n  Doppelteilzeit |     88.03      11.97 |    100.00 \n      Prekäre HH |     52.88      47.12 |    100.00 \nSingle, Vollzeit |     92.24       7.76 |    100.00 \nSingle, Teilzeit |     62.32      37.68 |    100.00 \n-----------------+----------------------+----------\n           Total |     83.14      16.86 |    100.00 \n```\n\n## Zusammensetzung von Armut (Spaltenprozent)\n\nWie hoch ist die Wahrscheinlichkeit einen bestimmten Haushaltstyp *innerhalb* der armutsbetroffenen Haushalte zu finden?\n\n``` {fontsize=\"\\\\small\"}\nErwerbskonstella |  Armutsgef. Haushalt\n            tion |      nein         ja |     Total\n-----------------+----------------------+----------\n         Rentner |     37.82      33.58 |     37.10 \n      Joblose HH |      2.79      27.30 |      6.92 \n Doppelverdiener |     10.24       0.20 |      8.55 \n Alleinverdiener |      7.10       3.28 |      6.46 \n     Zuverdiener |     12.63       1.48 |     10.75 \n  Doppelteilzeit |      1.10       0.74 |      1.04 \n      Prekäre HH |      2.03       8.93 |      3.20 \nSingle, Vollzeit |     21.00       8.72 |     18.93 \nSingle, Teilzeit |      5.29      15.78 |      7.06 \n-----------------+----------------------+----------\n           Total |    100.00     100.00 |    100.00 \n```\n\n## Typische Fragen zu typischen Unterschieden {.midi style=\"font-size: 70%\"}\n\n|  Fragestellung                                                               \t| Vergleich von                                                                    \t| Beispiel                                                                                                         \t|\n|------------------------------------------------------------------------------\t|----------------------------------------------------------------------------------\t|------------------------------------------------------------------------------------------------------------------\t|\n| Unterscheiden sich Gruppen in ihren typischen Ausprägungen?                  \t| Arithmetischen Mitteln, Medianen, Modi, Chancen, Risiken, Wahrscheinlichkeiten   \t|  $$\\Delta_G = \\bar{y}_F - \\bar{y}_M$$ Der (unbereinigte) gender wage gap ist die Differenz der durchschnittlichen Bruttostundenlöhne nach Geschlecht. \t|\n| Unterscheiden sich Gruppen in der typischen Streuung ihrer Ausprägungen?     \t| Varianzen, Standardabweichungen, Diversitäten                                    \t|  $$ F = \\sigma^2(y_M) / \\sigma^2(y_F) $$  Die Streuung der Löhne von Männern ist um den Faktor $F$ größer als die Streuung der Löhne von Frauen.                                                                       \t|\n| Unterscheidet sich die Art der Verteilung von Ausprägungen zwischen Gruppen? \t| Quantilen, Perzentilen, Dezilen | $$ \\Delta_{Q_G} = (Q_{90|M} / Q_{90|F}) - (Q_{10|M} / Q_{10|F})  $$ Die Lohnverteilung von Frauen ist vor allem im oberen Bereich im Vergleich zu denen der Männer komprimiert (Gläserne Decke).                  |        \n\n## Typische Werte: Notation & Begriffe {.midi style=\"font-size: 80%\"}\n\n+-------------+-----------------------+-------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Notation    | Bezeichnung           | Bedeutung                                                                     | Beispiel                                                                                                                                                                                         |\n+:============+:======================+:==============================================================================+:=================================================================================================================================================================================================+\n| $y_{Mod}$   | Modalwert             | Der Wert mit der höchsten Häufigkeit                                          | Die häufigsten gewünschten Arbeitsstunden waren 40h.                                                                                                                                             |\n+-------------+-----------------------+-------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| $\\tilde{y}$ | Median                | Der Wert der, die Verteilung in zwei gleich große relative Häufigkeiten teilt | 50% der Befragten wünschten sich eine Arbeitszeit von unter 35h und 50% wünschten sich eine Arbeitszeit ab 35h.                                                                                  |\n+-------------+-----------------------+-------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| $\\bar{y}$   | Arithmetisches Mittel | Durchschnitt         | Das arith. Mittel der gewünschten Arbeitsstunden lag im Jahr 2018 bei 32.8h. |\n+-------------+-----------------------+-------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n\n## Modalwert {.midi}\n\n::::: {.columns}\n:::: {.column width=\"30%\"}\n\n| Größe in cm |\n|:-----------:|\n|     160     |\n|   **165**   |\n|   **165**   |\n|   **165**   |\n|     173     |\n|     174     |\n|     176     |\n|     180     |\n|     180     |\n|     187     |\n\n::::\n\n:::: {.column width=\"70%\"}\nDer Modalwert oder Modus ist der **häufigste** Wert einer Verteilung. Es ist daher der Wert mit der größten relativen Häufigkeit.\n$$ y_{Mod} = 165   $$\n::::\n:::::\n\n\n## Median {.midi}\n\n::::: {.columns}\n:::: {.column width=\"20%\"}\n| Größe in cm |\n|:-----------:|\n|     160     |\n|   165   |\n|   165   |\n|   165 |\n|     *173*     |\n|     *174*     |\n|     176     |\n|     180     |\n|     180     |\n|     187     |\n::::\n\n:::: {.column width=\"80%\"}\nDer Median, ist der Wert, der 50% der oberen und 50% der unteren Werte eine Verteilung trennt. Der Median $\\tilde{y}$ von n **nach der Größe geordneten** Beobachtungen berechnet sich durch:\n\n$$\\tilde{y} = \\left\\{  \n\\begin{array}{l l}\n y_{\\frac{n+1}{2}} \\quad & \\text{bei ungerader Anzahl}\\\\[1em]\n \\frac{y_\\frac{n}{2} + y_{\\frac{n}{2}+1}}{2} \\quad & \\text{bei gerader Anzahl}\\\\\n \\end{array} \\right.$$\n\n$n$ bezeichnet die Anzahl der Beobachtungen. Bei 10 Beobachtungen bezeichnet $y_\\frac{10}{2} = y_5$ den **Wert** der fünften Beobachtung innerhalb der nach den *Y-Werten geordneten Verteilung*. Sie berechnen daher erst die **Stelle**, wo der Median in der Verteilung liegt und \"berechnen\" dann, den **Wert**, den der Median an dieser Stelle hat. \n\n::::\n:::::\n\n## Aritmethisches Mittel / Mittelwert {.midi}\n\n::::: {.columns}\n:::: {.column width=\"20%\"}\n| Größe in cm |\n|:-----------:|\n|     160     |\n|   165   |\n|   165   |\n|   165  |\n|     173     |\n|     174     |\n|     176     |\n|     180     |\n|     180     |\n|     187     |\n::::\n\n:::: {.column width=\"80%\"}\n\nDer Mittelwert ist das stärkste \"Arbeitspferd\" der Datenanalyse. Er ist das, was umgangssprachlich als \"Durchschnitt\" bezeichnet wird und berechnet sich durch: \n\n$$   \\begin{align}\n\\bar{y} &= \\dfrac{\\sum y_i}{N} \\nonumber \\\\\n&= \\frac{ 160 + 165 + 165 \\dots + 187}{10} = 172,5 \\nonumber\n\\end{align} $$ \n\nIm Kern ist das arithmetische Mittel ein \"Balance\"-Wert. Die Summe aller absoluten Differenzen zum Mittelwert unterhalb und oberhalb des arithmethischen Mittels sind identisch. \n\n::::\n:::::\n\n\n\n## Was ist das \"typische\" Alter des ersten Geschlechtsverkehrs? {.midi style=\"font-size: 60%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](16-VergleichsgegenstaendeI_files/figure-revealjs/unnamed-chunk-4-1.svg)\n:::\n:::\n\n\n## Alter des ersten Geschlechtsverkehrs nach Geschlecht {.midi style=\"font-size: 80%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](16-VergleichsgegenstaendeI_files/figure-revealjs/unnamed-chunk-5-1.svg)\n:::\n:::\n\n\n\n## Typische Unterschiedlichkeit: Notation & Begriffe {.midi style=\"font-size: 80%\"}\n\n| Notation  \t| Bezeichnung        \t| Bedeutung                                                                                                                                        \t|\n|-----------\t|--------------------\t|--------------------------------------------------------------------------------------------------------------------------------\t|\n|  $s^2$    \t| Varianz            \t| Die durchschnittliche, quadrierte Abweichung der Werte zum Mittelwert.                                                         \t|                                                                                                                 \t|\n|  s        \t| Standard- abweichung \t| Die durchschnittliche Abweichung der Werte zum Mittelwert.                                                                     \t| \n|  D        \t| Diversität         \t| Die Wahrscheinlichkeit zwei Untersuchungseinheiten mit unterschiedlichen Ausprägungen zufällig aus der Stichprobe zu ziehen.   \t|   \n\n\n\n## Varianz\n\nEin Maß für die Unterschiedlichkeit von Werten ist die **Varianz**. Sie ist die *durchschnittliche* quadrierte Abweichung zum arithmetischen Mittel (und damit eine Sonderform des arithmetischen Mittels). \n\n$$\ns^2 = \\frac{\\sum(y_i - \\overline{y})^2}{n}\n$$\n\n## Varianz {.midi}\n\n\n::::: {.columns}\n:::: {.column width=\"20%\"}\n| Größe in cm |\n|:-----------:|\n|     160     |\n|   165   |\n|   165   |\n|   165  |\n|     173     |\n|     174     |\n|     176     |\n|     180     |\n|     180     |\n|     187     |\n::::\n\n:::: {.column width=\"80%\"}\n\n$$\n\\begin{align}\ns^2 &= \\frac{\\sum\\limits_{i=1}^n(y_i - \\overline{y})^2}{n} \\nonumber \\\\\n    &= \\frac{(160 - 172,5)^2 + (165 - 172,5)^2 \\dots + (187 - 172,5)^2}{10} = 66.25 \\nonumber\n\\end{align}\n$$\n\n\n\n::::\n:::::\n\n## Standardabweichung\n\nWir wollen nicht wissen, was die durchschnittliche \"quadrierte Differenz\" ist, sondern, was die \"typischen Unterschiedlichkeit\" der Befragten ist. Um eine sinnvolle, inhaltliche Interpretation zu ermöglichen, muss die Wurzel aus der Varianz gezogen werden. Diese Wurzel bezeichnet man als *Standardabweichung*.\n\n$$\n\\begin{equation}\n  s = \\sqrt{s^2}\n\\end{equation}\n$$\n\nDa $\\sqrt{66,25} \\approx 8,14$ ist die typische Abweichung der Körpergrößen zwischen den beobachteten Personen 8,14 cm. \n\n## Reminder: Warum ist das relevant? \n\n<iframe width=\"100%\" height=\"100%\" src=\"https://019d86ab-8f95-cd27-439b-478f5d4f4fe1.share.connect.posit.cloud\" ></iframe>\n\n## Diversität {.midi}\n\nIn einigen Fällen ist eine Berechnung eines Mittelwerts nicht sinnvoll.[^1] Dennoch möchten wir dann eine Möglichkeit haben, die Unterschiedlichkeit der verteilten Werte auszudrücken. Eine Möglichkeit, diese Unterschiedlichkeit zu messen, besteht in Diversitäts-Maßen, wie dem Simpson Diversitäts Index:  \n\n$$ D = 1 - \\sum\\limits_{y}^Y P(y)^2 $$\n\ny ist eine Ausprägung des Merkmals Y, Y die Anzahl aller Ausprägungen, und N die Gesamtanzahl aller Beobachtungen ist. Der Index drückt die Wahrscheinlichkeit aus, durch eine Ziehung zwei \\textit{unterschiedlich ausgeprägte} Beobachtungen zu erhalten. D schwankt zwischen 0 und 1. Ist D = 1, liegt höchste Diversität vor. \n\n[^1]: Das sind vor allem: Verteilungen mit nominalen oder ordinal gemessenen Ausprägungen mit sehr unterschiedlichen Intervallen.\n\n\n## Belastung durch Arbeitsstunden {.midi}\n\n::: {.columns}\n\n::: {.column style=\"font-size: 80%\"}\n**Wie stark sind Sie durch Ihre Arbeitsstunden belastet?**\n\n\n| Belastung  | Männer | Frauen | Gesamt |\n|:-----------|-------:|-------:|-------:|\n| Gar nicht  |    854 |    747 |  1,601 |\n| Mäßig      |  4,033 |  3,399 |  7,432 |\n| Stark      |  2,459 |  2,186 |  4,645 |\n| Sehr stark |    588 |    553 |  1,141 |\n| Gesamt     |  7,934 |  6,885 | 14,819 |\n\n:::\n\n::: {.column}\n\n Die Diversität der Angaben über alle Befragten lässt sich wie folgt berechnen:\n\n::: {style=\"font-size: 50%\"}\n\n$$ D = 1 - \\left( (\\dfrac{1601}{14819})^2 + (\\dfrac{7432}{14819})^2 + (\\dfrac{4645}{14819})^2 + (\\dfrac{1141}{14819})^2 \\right) = 0.633 $$\n:::\n\nWürden wir zwei Befragte zufällig ziehen, erhielten wir daher mit einer Wahrscheinlichkeit von 63.3% unterschiedliche Angaben. Die Diversität innerhalb von Männern ist 0.628 und innerhalb von Frauen 0.637.\n\n:::\n\n:::\n\n\n\n\n\n",
    "supporting": [
      "16-VergleichsgegenstaendeI_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}