project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "*.docx"

website:
  page-navigation: true
  favicon: images/favicon-2.png
  title: "Methoden empirischer Sozialforschung"
  description: "Webpage für das Modul 'Sozialwissenschaftliche Methoden I'"
  site-url: "https://methoden.empirischer.sozialforschung.netlify.com"
  repo-url: https://github.com/HauptSoc/grundlagen.emp.soz
  repo-actions: [issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Andreas Haupt"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/mindmap-logoV2.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/HauptSoc/grundlagen.emp.soz
        text: "GitHub organization"
      - icon: cloud-fill
        href: https://posit.cloud/
        aria-label: RStudio Cloud
      - icon: person-fill
        href: https://campus.kit.edu
        text: "ILIAS KIT"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Wissenswertes"
        contents:
          - href: course-overview.qmd
            text: Ziele
          - href: index.qmd
            text: Was, wann, welche Reihenfolge?
          - href: course-team.qmd
            text: Das Team
          - href: course-syllabus.qmd
            text: Das Kleingedruckte

format:
  html:
    theme:
      light: [cosmo, style/stat331.scss]
      dark: [cosmo, style/stat331.scss, style/dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

execute:
  freeze: auto

editor: visual