---
title: "Grundlagen empirischer Sozialforschung"
tbl-colwidths: [5,15,45,5,5,5,5,5]
---

# Sommersemester: Datenanalyse

| Woche | Termin | Thema | Lektüre | Folien | Übungen | Aufgabenblätter | Vertiefungen |   |   |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|--------|--------|
|  |  | **I. Grundlagen guten Vergleichens** |  |  |  |  |  |  |  |
| 1 | 21.04. | Vergleiche und Verteilungen | 📖 | [🖥](slides/15-slides.qmd) | ✍ |  |  |  |  |
| 2 | 28.04. | Vergleichsgegenstände I | 📖 | [🖥](slides/00-slides.qmd) | ✍ |  |  |  |  |
| 3 | 05.05. | Vergleichsgegenstände II | 📖 | [🖥](slides/00-slides.qmd) | ✍ |  |  |  |  |
|  |  | **II. Der Vergleich zwischen beeinflussten und weniger beeinflussten Gruppen** |  |  |  |  |  |  |  |
| 4 | 12.05. | Einfache lineare Modelle I | 📖 | [🖥](slides/00-slides.qmd) | ✍ |  |  |  |  |
| 5 | 19.05. | Einfache lineare Modelle II | 📖 | [🖥](slides/00-slides.qmd) | ✍ |  |  |  |  |
| 6 | 26.05. | Pfingsten |  |  |  |  |  |  |  |
| 7 | 02.06. | Varianzanalyse | 📖 | [🖥](slides/00-slides.qmd) | ✍ |  |  |  |  |
|  |  | **III. Die Isolation von Einflüssen für gute Vergleiche** |  |  |  |  |  |  |  |
|  | 09.06. | Komplexe Daten generierende Prozesse I | 📖 | [🖥](slides/00-slides.qmd) | ✍ |  |  |  |  |
| 8 | 16.06. | Komplexe Daten generierende Prozesse II | 📖 | [🖥](slides/00-slides.qmd) | ✍ |  |  |  |  |
| 9 | 23.06. | Multivariate, lineare Modelle | 📖 | [🖥](slides/00-slides.qmd) | ✍ |  |  |  |  |
|  |  | **IV. Der Vergleich mit Zufallsprodukten** |  |  |  |  |  |  |  |
| 10 | 30.06. | Konfidenzintervalle | 📖 | [🖥](slides/00-slides.qmd) | ✍ |  |  |  |  |
| 11 | 07.07. | Signifikanz I: Nullhypothesen, t-Tests | 📖 | [🖥](slides/00-slides.qmd) | ✍ |  |  |  |  |
| 12 | 14.07. | Signifikanz II: p-Values, Bedeutsamkeit | 📖 | [🖥](slides/00-slides.qmd) | ✍ |  |  |  |  |
| 13 | 21.07. | Klausurvorbereitung | 📖 | [🖥](slides/00-slides.qmd) | ✍ |  |  |  |  |
| 14 | 28.07. | Klausur |  |  |  |  |  |  |  |

# Wintersemester: Datenerhebung

| Woche | Termin | Thema | Lektüre | Folien | Übungen | Aufgabenblätter | Vertiefungen |
|:-------:|---------|---------|:-------:|:-------:|:-------:|:-------:|:-------:|
| 1 | 30.10. | Methoden - Was soll das? | [📖](https://link.springer.com/rwe/10.1007/978-3-658-39759-3_21-1 "Schamlose Eigenwerbung") | [🖥](slides/00-slides.qmd) |  |  | [📁](misc\01-zusatz.qmd) |
| 2 | 06.11. | Wissenschaftliche Spielregeln | [📖](https://www.scientificamerican.com/article/what-happens-when-an-entire-scientific-field-changes-its-mind/ "Wissenschaftliche Revolutiönchen") | [🖥](slides/01-slides.qmd "Wissenschaftliche Spielregeln") |  |  |  |
|  |  | **I. Unterschiede messen** |  |  |  |  |  |
| 3 | 13.11. | Grundlagen guten Unterscheidens | [📖](https://flowingdata.com/2016/07/20/modern-family-structure/ "Welche unterschiedlichen Haushaltsformen gibt es da draußen?") | [🖥](slides/02-slides.qmd "Grundlagen guten Unterscheidens") | [✍](exercises/01-ex.qmd) |  |  |
| 4 | 20.11. | Dimensionen, Typen, Ausprägungen | 📖 | [🖥](slides/03-slides.qmd) | [✍](exercises/02-ex.qmd) |  |  |
| 5 | 27.11. | Messtheoretische Grundlagen | [📖](https://link.springer.com/content/pdf/10.1007/978-3-658-21308-4_107.pdf "Blasius (2019): Skalierung") | [🖥](slides\04-slides.qmd "Messtheoretische Grundlagen") | [✍](exercises/03-ex.qmd) |  | [📁](misc\05-zusatz.qmd) |
| 6 | 04.12. | Skalierung | [📖](https://link.springer.com/content/pdf/10.1007/978-3-658-21308-4_62.pdf "Latcheva & Davidov (2019)") | [🖥](slides\05-slides.qmd) | [✍](exercises/04-ex.qmd) |  |  |
| 7 | 11.12. | Ausprägungen kombinieren | [📖](https://link.springer.com/chapter/10.1007/978-3-658-21308-4_62) | [🖥](slides\06-slides.qmd) |  |  |  |
|  |  | Itemkonstruktion | [📖](https://link.springer.com/chapter/10.1007/978-3-658-37985-8_64) | [🖥](slides\07-slides.qmd) | [✍](exercises/05-ex.qmd) |  |  |
| 8 | 18.12. | Reaktionen erfassen | [📖](https://link.springer.com/chapter/10.1007/978-3-658-21308-4_58) | [🖥](slides\08-slides.qmd) |  |  |  |
| 9 | 08.01. | Reliabilität und Validität | [📖](https://link.springer.com/chapter/10.1007/978-3-531-92038-2_11) | [🖥](slides\09-slides.qmd) | [✍](exercises/06-ex.qmd) |  |  |
|  | ab. 14.1. |  |  |  |  | [📋](https://ilias.studium.kit.edu/goto.php/crs/2757061) |  |
|  |  | **II. Unterschiede erheben** |  |  |  |  |  |
| 10 | 15.01. | Stichprobenziehung | 📖 | [🖥](slides\10-slides.qmd) | [✍](exercises/07-ex.qmd) |  |  |
| 11 | 22.01. | Teilnahmeselektion | 📖 | [🖥](slides\11-slides.qmd) | [✍](exercises/08-ex.qmd) |  |  |
| 12 | 29.01. | Antwortverweigerung | 📖 | [🖥](slides\12-slides.qmd) | [✍](exercises/09-ex.qmd) | 📋 |  |
|  |  | **III. Die richtigen Unterschiede erfassen** |  |  |  |  |  |
| 13 | 05.02. | Untersuchungsdesigns - Season 1 | 📖 | [🖥](slides\13-slides.qmd) | [✍](exercises/10-ex.qmd) |  |  |
| 14 | 12.02. | Untersuchungsdesigns - Season 2 | 📖 | [🖥](slides\14-slides.qmd) | ✍ |  |  |