---
title: "Model Selection"
format: 
  html: 
    number-sections: true
    number-depth: 2
    section-divs: true
editor: source
execute: 
  echo: true
  warning: false
  message: false
---

```{r}
#| include: false
#| label: packages-functions-sourced
source("_common.R")

set.seed(1234)
```

# Textbook Reading Part 1 -- Due by Monday

[**Required Reading:** Model Selection](chapters/week-6-reading1.qmd)

::: callout-note
## Reading Guide -- Due Monday by the beginning of class

[Download the Word Document](reading-guide/week6-reading1.docx)
:::

# Textbook Reading Part 2 -- Due by Wednesday

[**Required Reading:** Sampling Variability](chapters/week-6-reading2.qmd)

::: callout-note
## Reading Guide -- Due Wednesday by the beginning of class

[Download the Word Document](reading-guide/week6-reading2.docx)
:::

# Concept Quiz -- Due Monday by the start of class

**Question 1** -- $R^2$ is the \[correlation / percent\] of variation in the \[explanatory / response\] variable that is explained by the \[response variables / explanatory variables\] and the \[decided model / best model / linear model\].

**Question 2** -- Adjusted $R^2$ should be used for \[simple / multiple\] linear regression and unadjusted $R^2$ should be used for \[simple / multiple\] linear regression.

**Question 3** -- In the adjusted $R^2$ formula $n$ represents the \[number of explanatory variables / sample size / response variable\] and $k$ represents the \[number of explanatory variables / sample size / number of coefficients needed to be calculated\].

**Question 4** -- When choosing a model based on adjusted $R^2$, the model with the \[lowest / highest\] value should be chosen.

**Question 5** -- Backward selection starts with the model with \[no / every\] explanatory variable included.

**Question 6** -- Backward selection \[adds / removes\] variables from the model. If the \[R-squared / correlation / adjusted R-squared\] when the variable is \[added / removed\] is \[smaller / larger\], the variable will be \[added / removed\] from the final model.

**Question 7** -- Forward selection starts with the model with \[no / every\] explanatory variable included.

**Question 8** -- Forward selection \[adds / removes\] variables from the model. If the \[R-squared / correlation / adjusted R-squared\] when the variable is \[added / removed\] is \[smaller / larger\], the variable will be \[added / removed\] from the final model.

# R Tutorials 

::: {.callout-important}
# Note that one is due on Monday and one is due on Wednesday!
:::

**Due Monday:** [Assessing Model Fit](https://openintro.shinyapps.io/ims-03-model-05/#section-assessing-model-fit)

**Due Wednesday:** [Foundations of Inference](https://openintro.shinyapps.io/ims-04-foundations-01/)
