---
title: "Week 10: Two-Way ANOVA"
format: 
  html: 
    number-sections: true
    number-depth: 2
    section-divs: true
editor: source
execute: 
  echo: true
  warning: false
  message: false
---

```{r}
#| include: false
library(tidyverse)
library(emo)
library(gridExtra)
```

Welcome!

This week we explore one final area of ANOVA, a situation where we have multiple explanatory variables. This is called a **two-way ANOVA**. A two-way ANOVA extends the one-way ANOVA to situations with two categorical explanatory variables. This new methods allows researchers to simultaneously study two variables that might explain variability in the responses and explore whether the impacts of one explanatory variable change depending on the level of the other explanatory variable.

# Textbook Reading

To be honest, I didn't have the energy this week to write another chapter on two-way ANOVA. So, instead we will be reading a couple of sections out of another statistics textbook. I've uploaded the PDFs of these sections to OneDrive, so you should be able to read them online or download them.

https://tuos-bio-data-skills.github.io/intro-stats-book/anova-for-randomised-block-designs.html


### Reading Guide -- Due Monday by the start of Class

[Download the Word Document](reading-guide/week10-reading.docx)

## Concept Quiz -- Due Monday by the start of class

**1. Match each two-way ANOVA model to its correct description.**

::::: columns
::: {.column width="40%"}
</br>

**additive model**

</br> </br> </br>

**interaction model**
:::

::: {.column width="60%"}
The relationship between one factor and the response changes depending on the level of another factor.

</br>

The relationship between one factor and the response remains the same across all levels of another factor.

</br>

There is a significant relationship between each factor and the response.
:::
:::::

</br>

**2. Match each two-way ANOVA model to its multiple linear regression counterpart.**

:::::: columns
::: {.column width="45%"}
**additive model**

**interaction model**
:::

::: {.column width="10%"}
:::

::: {.column width="45%"}
different slopes

parallel slopes
:::
::::::

</br>

<!-- **3. If there is evidence of an interaction when visualizing a two-way ANOVA model we will see...** -->

<!-- -   differences in the centers of the distributions -->

<!-- -   differences in the spreads of the distributions -->

<!-- -   similar profiles of the distributions across the facets -->

<!-- -   differences in the profiles of the distributions across the facets -->

<!-- </br> -->

**3. Which of the following are conditions of a two-way ANOVA model?** (Select all that apply)

-   independence of observations between the groups
-   independence of observations within each group
-   independence of variables
-   normally distributed responses within each group
-   normally distributed residuals
-   linear relationship between the explanatory and response variables
-   equal variance of residuals
-   equal variance of responses within each group

</br>

**4. Which of the following is important to consider when assessing independence?** (Select all that apply)

-   If the same observational unit (e.g., person, penguin, tree) could be sampled multiple times

-   If observations could be biologically related (e.g., parents, siblings, etc.)

-   If observations could be spatially related (e.g., countries that border each other)

-   If there is a relationship between the observations and the response variable

</br>

<!-- **6. An \[additive / interaction\] model is fit using a `*` symbol between the explanatory variables.** -->

<!-- </br> -->

**5. \[True or False\] When an additive model is fit, the interpretation of the p-value associated with each explanatory variable is \[conditional / independent\] on the other explanatory variable(s) in the model.**

</br>

**6. If the null hypothesis is rejected in an additive two-way ANOVA model, what model should be fit instead?**

-   separate one-way ANOVA models
-   a one-way ANOVA model containing the variable with the smallest p-value (from the additive two-way ANOVA)
-   a mean only model
-   an interaction two-way ANOVA model
-   a simple linear regression

</br>

## R Tutorial -- Due Wednesday by the start of class

This week's R tutorial is a short guide stepping you through model selection starting with a two-way ANOVA interaction model.

[Click here to access this week's R tutorial](https://rstudio.csm.calpoly.edu/twa/)

::: callout-note
# Submission

Submit a screenshot of the completion page at the end of the tutorial.
:::
