---
title: "Week 8 -- Conditions for Inference & One-Way ANOVA"
format: 
  html: 
    number-sections: true
    number-depth: 2
    section-divs: true
editor: source
execute: 
  echo: true
  warning: false
  message: false
---

# Textbook Reading

First, we are going to refresh on the conditions for linear regression. You 
might want to reference last week's reading while completing the first reading
guide: [**Model Conditions for Linear Regression**](chapters/week7-reading2.qmd)

::: callout-note
## Reading Guide -- Due Monday by the start of class

There are a few questions from this that are similar to the of last week's
reading guide. Feel free to copy and paste your previous answers to this 
reading guide! 

[Download the Word Document](reading-guide/week8-reading1.qmd)
:::

Now, let's read about how hypothesis testing extends into multiple linear
regression. This allows us to connect to our new topic---ANOVA! 

[**Required Reading:** Hypothesis Tests for Multiple Linear Regression](chapters/week-8-reading-mlr.qmd)

::: callout-important
There is no reading guide for this chapter, just a concept quiz! 
:::

# Concept Quizzes

We have two concept quizzes this week, one that is due by Monday (on model
conditions) and one that is due by Wednesday (on ANOVA). 

## Due Monday by the start of class

**1. What are the required conditions for linear regression?** (select all that apply)

-   a random sample was taken
-   equal variance of residuals
-   a large sample was collected
-   linear relationship between x and y
-   independence of observations
-   independence of variables
-   normality of residuals
-   normality of observations

**2. In the scatterplot of stem dry mass versus stem length, what condition appears to be violated?** (select all that apply)

-   equal variance of residuals
-   linear relationship between x and y
-   independence of observations
-   normality of residuals

**3. Which of the following would violate the condition of independence?** (select all that apply)

-   collecting a non-random sample
-   observations related geographically (spatially)
-   observations that are related in time (temporally)
-   repeated observations on the same person
-   observations related biologically

**4. When conducting a hypothesis test (in general), we assume the \[observations / variables\] are independent. When conducting a hypothesis test for a linear regression, the conditions require that the \[observations / variables\] are independent.**

## Due Wednesday by the start of class

::: {.callout-important}
# Will be posted by Friday evening! I'm still putting together the questions! 
:::

# R Tutorial -- Due Monday by the start of class (note the new time!)

[**Required Tutorial:** Evaluating the technical conditions in linear regression](https://openintro.shinyapps.io/ims-06-model-infer-04/)


