## (ohne Titel)

# Dimensionalität

##  {#section .unnumbered}

## Dimensionen

Die theoretische Grundlage unserer Unterscheidungen kann unterschiedich komplex sein.

- Nehmen wir an, dass die Unterschiede nur auf einer Sache beruhen, die sich auch nicht in kleinere Bestandteile zerlegen lassen, dann nutzen wir eine **eindimensionale** Unterscheidung (Alter, Geschlecht, Arbeitsstunden).

- Unterschiede können jedoch auch auf einer Kombination von Bestandteilen basieren, die für sich jeweils eigene Wirkungen oder Bedeutungen haben und sich ggf. auch unabhängig voneinander verändern oder sich kompensieren können. In diesem Fall nutzen wir eine **mehrdimensionale** Unterscheidung (sozialer Status, Persönlichkeitsstruktur).

## Dimensionen & Ausprägungen

:::::: center
:::: minipage
::: center
:::

\
::::

::: minipage
Konstrukte bestehen immer aus Dimensionen, die wiederum Ausprägungen haben.\
Ausprägungen sind theoriegeleitet und nicht notwendigerweise erschöpfende Beschreibungen der Vielfalt eines Phänomens.\
Die Ausprägungen können unterschiedlich strukturiert sein (Nullpunkt, gleiche Abstände, Ränge, Typen).
:::
::::::

## Eigenschaften von Ausprägungen

::: center
[Quelle](https://datatab.de/tutorial/skalenniveau)
:::

Diese verschiedenen Eigenschaften von Ausprägungen werden auch als *Skalenniveau* bezeichnet. Je höher das Skalenniveau von Ausprägungen ist (Pfeilrichtung nach rechts), desto detailliertere Unterschiede können wir mit Ihnen erfassen und desto mehr (statistische) Vergleichsmöglichkeiten haben wir.

## Skalenniveaus

## Dimensionen & Ausprägungen

:::::: center
:::: minipage
::: center
\
:::

\
\
::::

::: minipage
Unterscheidungen, wie nach dem *sozialen Status* einer Person, können auf mehreren Dimensionen beruhen.\
Die Dimensionen können in unterschiedlichem Zusammenhang zueinander und zum Gesamtkonstrukt stehen.\
Jede Dimension besitzt Ausprägungen.\
Die Kombination aus den Ausprägungen pro Dimension ergibt die Ausprägung für die Untersuchungseinheit im Gesamtkonstrukt.
:::
::::::

## Intelligenzmessung

::: center
:::

[Deary, Ian J (2013): Intelligence. *Current Biology* (23)16, 673-676](https://www.sciencedirect.com/science/article/pii/S0960982213008440)

## Dimensionen beruflicher Selbstregulation

:::::: center
:::: minipage
::: center
:::

\
[Menge, C. & Schaeper, H. (2019): Berufliche Selbstregulation von Lehrkräften: Überprüfung eines Kurzinstruments. *Zeitschrift für Erziehungswissenschaften* 22, 1489--1513](https://link.springer.com/article/10.1007/s11618-018-0851-x)
::::

::: minipage
- Berufliche Selbstregulation besteht aus zwei Dimensionen:

  - berufliches Engagement

  - Widerstandsfähigkeit

- Beide Dimensionen korrelieren moderat negativ miteinander ($r = -0.37$).

- Die beiden Dimensionen höherer Ordnung bestehen selbst wiederum aus zwei Unterdimensionen.
:::
::::::
