## (ohne Titel)

# Validität {#validität .unnumbered}

##  {#section .unnumbered}

## Validität

Ein Merkmal wird valide gemessen, wenn das Messinstrument tatsächlich das Merkmal misst -- und nicht *systematisch* etwas anderes als man möchte.

Im Unterschied zur Reliabilität beziehen sich Probleme der Validität auf *systematische* Fehler bei der Messung. Theoretisch kann ein Messinstrument sehr reliabel aber nicht valide sein. Wir können zum Beispiel systematisch eine Subdimension bei der Messung nicht einbeziehen, die anderen Subdimensionen eines Merkmals aber sehr reliabel messen.

## Systematische Störungen von Messungen

:::::: columns
:::: column
.5

::: center
:::
::::

::: column
.5 **Problem 1: Ein Teil der Messung bezieht sich systematisch auf einen anderen Faktor.**\
\
Im linken Modell soll $F_1$ mit vier Items gemessen werden. Reaktionen auf $I_4$ werden aber systematisch von einem anderen Faktor $F_2$ verursacht, der mit $F_1$ korreliert ist. Nur deshalb besteht auch eine Korrelation zwischen $I_4$ und $F_1$.\
Bsp: Wir wollen Leistungsfähigkeit u.a. durch schulische Hausaufgaben messen und messen dadurch systematisch auch den Einfluss des elterlichen Umfelds.
:::
::::::

## Systematische Störungen von Messungen

:::::: columns
:::: column
.5

::: center
:::

\
\
::::

::: column
.5 **Problem 2: Die Störfaktoren sind nicht zufällig.**\
\
Wir haben bisher angenommen, dass die Störfaktoren zufällig sind. Allerdings können diese auch systematisch sein. Im Modell werden die Störfaktoren von $I_2$ und $I_3$ von einem (nicht erfassten) Faktor $F_3$ beeinflusst. Da die beiden Störfaktoren systematisch von der gleichen Eigenschaft beeinflusst werden, sind diese auch nicht mehr voneinander unabhängig, sondern miteinander korreliert.

Bsp: Die Angabe von Schmerz durch Schmerzskalen ist u.a. davon abhängig, in welcher Geschlechter-Relation Befragte und Fragende zueinander stehen.
:::
::::::

## Arten von Validität

In der Literatur werden verschiedene Formen von Validität diskutiert, die im Kern verschiedene Facetten der **Gültigkeit** der wissenschaftlichen Untersuchung darstellen.\

Historisch wurden viele verschiedene Formen von Validiät eingeführt. Mittlerweile werden für Messungen vor allem zwei Formen verwendet:

1.  Konstruktvalidität

2.  Kriteriumsvalidität

Darüber hinaus gibt es noch zwei weitere Formen von Validität, die sich auf die Gültigkeit der gesamten Untersuchung beziehen.

1.  interne Validität

2.  externe Validität

<!-- -->

1.  *Konstruktvalidität:* Wurden alle Dimensionen des Merkmals gemessen oder weniger oder Dimensionen, die nicht zum Merkmal gehören?

    - Diese Frage können Sie nur dann sinnvoll beantworten, wenn Sie vorher eine klare Konzeptspezifikation durchgeführt haben und es damit auch von anderen Konzepte, die potentiell in Zusammenhang mit Ihrem Konzept stehen könnten, abgegrenzt haben.

    - Typischerweise diskutieren Forschende bei der Konstruktvalidität die Fragen, ob ein Konstrukt uni- oder mehrdimensional ist oder ob man eine Subdimension vergessen hat.

    - Bsp: Ist Einsamkeit ein- oder mehrdimensional (quantitativ vs. qualitative Formen von Einsamkeit)? Messen wir Armut zu unterkomplex, wenn wir lediglich das Einkommen einbeziehen? Haben wir alle Formen kognitiver Haushaltsarbeit erfasst?

2.  *Kriteriumsvalidität:* Steht das gemessene Konstrukt empirisch in erwarteten Zusammenhängen zu anderen Konstrukten?

    - Bei dieser Form von Validität geht es darum, ob ein Konstrukt

      - in Zusammenhang mit Konstrukten steht mit denen es bekanntermaßen einen Zusammenhang bildet (Einsamkeit $\leftrightarrow$ Depression).

      - in Zusammenhang mit Konstrukten steht, die neu theoretisch erwartet werden (Einsamkeit $\rightarrow$ Ausbildungsabbruch).

      - *nicht* oder nur in begrenztem Maß in Zusammenhang mit Konzepten steht, die etwas anderes messen (Einsamkeit $\not\leftrightarrow$ Familienform).

3.  *interne Validität:* Maximale interne Validität liegt vor, wenn der studierte Zusammenhang zwischen den Eigenschaften nicht durch weitere (unbeobachtete) Einflussgrößen zurückzuführen ist.

    - Interne Validität bezieht sich auf die Isolation von Einflüssen. Dies kann durch die Art des Untersuchungsdesigns geschehen (siehe: Randomisierung) oder durch explizite Modellierung aller korrelierter Einflüsse (siehe: Drittvariablenkontrolle).

    - Wenn Sie für die interne Validität Ihrer Untersuchung plädieren, müssen Sie Zweifel ausräumen, dass Eigenschaften "im Hintergrund" für (einen Teil) der Ergebnisse verantwortlich sind.

    - Studien, die Diskriminierung im Arbeitsmarkt messen wollen, müssen klar machen, dass die Differenzen zwischen Gruppen nicht auch durch unterschiedliche Präferenzen oder unterschiedliches Verhalten verursacht wird.

4.  *externe Validität* Maximale externe Validität liegt dann vor, wenn die Ergebnisse der Untersuchung nicht nur für den Kontext der Untersuchung, sondern für die gesamte Population gelten.

    - Externe Validitität bezieht sich auf die Generalisierbarkeit Ihrer Mess- und Untersuchungsergebnisse (siehe: Inferenzstatistik).

    - Selektive Stichproben (z.B. Untersuchungen mit Studierenden) können Zusammenhänge zeigen, die in der gesamten Population anders sind.

    - Ergebnisse von Untersuchungen innerhalb spezifischer Kontexte (Berufsbildungssysteme, Kulturen, Organisationsformen) können auch auf andere Kontexte teilweise übertragbar sein.
