---
title: "Midterm Project Feedback & Model Selection"
format: 
  revealjs:
    theme: style.scss
editor: source
---

## Deadline Reminders

-   Lab 3 revisions are due tonight
-   Statistical Critique 1 revisions are due tonight
-   The final version of your Midterm Project is due Sunday at midnight

::: callout-important
# Deadline Extensions

You **cannot** request deadline extensions for the final version of your Midterm
Project. The assignment portal closes at 11:59pm on Sunday. 
**Do not ride the line. Submissions made after 11:59pm will not be accepted.**
:::

# Midterm Project Review

## Data Descriptions

Your Introduction should **at a minimum** address the following questions:

1. Who collected the data?
2. How were the data collected?
3. When were the data collected?
3. Why were the data collected? 
4. What question do these data address? 

::: {.callout-important}
# Are your data associated with a publication?

If so, you should have a reference to this publication in your Introduction!
:::

## Research Questions

::: incremental
-   Your research question should be a [question]{.underline}

-   Your question should be able to be addressed with a [multiple linear regression]{.underline}

    -   Is the relationship between stem length and stem dry mass different for watersheds treated with calcium versus without?
    -   Is there a relationship between the elevation a pika lives and its stress levels? Does this relationship differ for male and female pika?
:::

## Variables

> Describe the response and explanatory variables, how they were measured and
their associated units. 

::: {.incremental}
- How were the variables measured? 
  * How do you know?
  * If the researchers do not explicitly state how a variable was measured, 
  don't guess! Be transparent about information you do not know!
:::

## Data Visualizations & Coefficient Interpretations

::: incremental
-   Descriptions of your visualizations should address:

    -   form, direction, strength, and unusual points

-   Descriptions of your visualizations should go **immediately below** the visualization, *before* the "Statistical Methods" subsection.
:::

## Study Limitations -- Scope of Inference

Based on how the study was designed, what population can you infer these results onto?

:::: fragment
::: small
-   Every penguin?
-   Penguins in Antarctica?
-   Penguins on the Biscoe, Dream, and Torgersen islands?
-   Penguins in similar areas to those that were sampled?
-   This sample of penguins?
:::
::::

## Study Limitations -- Scope of Inference

Based on how the study was designed, what population can you infer these results onto?

::: small
**Justify** what population you believe your analysis can be inferred onto.

-   The sample of \[possums / professors / crabs\]?
-   Some larger population of \[possums / professors / crabs\]?

Your justification needs to connect with how the researchers collected their data!
:::

## Study Limitations -- Causal Inference

Based on how the study was designed, what can you say about the relationships between the variables?

</br> 

:::: fragment
::: small
-   Can you say that your explanatory variable(s) [causes]{.underline} changes in your response variable?
-   Why or why not?
-   What can you say about these relationships?
:::
::::

## Study Limitations -- Causal Inference

Based on how the study was designed, what can you say about the relationships between the variables?

</br> 

::: small
Stating that the study was "observational" doesn't tell me that you understand what would be required to use cause-and-effect language!

-   What **specifically** would have the researchers have needed to do in order to use causal language?
:::

## Writing Conclusions

-   Circle back to your research question
-   What did you learn in your visualizations?
-   What did you learn in your regression model?
-   What conclusions would you reach about your research question?

::: callout-caution
# No "significance" & no p-values
:::

# Model Selection

# Lab 6

## Forward Selection (by Hand)

1.  Start with the most basic model (one mean)

2.  Decide which **one** variable to add (based on adjusted $R^2$)

3.  Decide if you should add another variable

$\vdots$

4.  Stop adding variables when adjusted $R^2$ stops increasing

## A More Automated Option

```{r}
#| eval: false
#| label: code-from-lab
#| echo: true
#| code-line-numbers: "|2,6,7"

evals_train %>% 
  map(.f = ~lm(score ~ .x + <VARIABLES SELECTED>, data = evals_train)) %>% 
  map_df(.f = ~get_regression_summaries(.x)$adj_r_squared) %>% 
  select(-ID, 
         -score,
         -<VARIABLE 1 SELECTED>,
         -<VARIABLE 2 SELECTED>
         ) %>% 
  pivot_longer(cols = everything(), 
               names_to = "variable", 
               values_to = "adj_r_sq") %>% 
  slice_max(adj_r_sq)
```
