## (ohne Titel)

# Ausprägungen kombinieren

##  {#section .unnumbered}

## Die Ordnung von Gesamtausprägungen

Besteht das Konstrukt aus verschiedenen Dimensionen, müssen die Ausprägungen jeder einzelnen Dimension in Kombination gesetzt werden.

- Ist das Resultat dieser Kombination eine metrische Unterscheidung, wird dies auch als *Skala* oder *Index* bezeichnet.

- Ist das Resultat eine ordinale oder nominale Unterscheidung, wird dies auch als Typisierung bezeichnet.

# Indexbildung {#indexbildung .unnumbered}

##  {#section-1 .unnumbered}

## Indexbildung

Werden die Ausprägungen (der verschiedenen Dimensionen) eines Merkmals metrisch gemessen, lässt sich mit ihnen ein Index konstruieren. Manche Indexbildungen beruhen auf der Annahme, dass sich alle Werte gleichwertig zu seinem Gesamtwert (=Index) aufsummieren. Das muss aber nicht der Fall sein. Wir können drei Formen der Indexbildung unterscheiden und müssen stets begründen, warum wir welche Form benutzen.

- Additive Indizes: $I= X_1 + X_2 + X_3$

- Gewichtete Indizes: $I= a \cdot X_1 + b \cdot X_2 + c \cdot X_3$

- Multiplikative Indizes: $I = X_1 \cdot X_2 \cdot X_3$

Einen gewichteten Index benötigen wir, wenn verschiedene Items oder Dimensionen für das Endergebnis unterschiedlich bedeutsam sind. Einen multiplikativen Index benötigen wir, wenn alle Items sich auf notwendige Bedingungen einer Eigenschaft beziehen.

## Bedeutung der Einzeldimensionen für sozialen Status

:::::: center
:::: minipage
::: center
\
:::

\
\
::::

::: minipage
Für die Unterscheidung von Personen nach ihrem sozialen Status sind drei Dimensionen bedeutsam.\
Es ist aber unplausibel, dass sozialer Status in allen Kontexten sich gleichbedeutend aus allen drei Dimensionen ableitet. Manche Kapitalsorten sind in spezifischen Kontexten bedeutsamer als andere und benötigen daher auch ein größeres Gewicht im Gesamtindex für den sozialen Status.
:::
::::::

## German Index of Multiple Deprivation

::: center
:::

[Quelle](http://tinyurl.com/guca8ah)

## German Index of Multiple Deprivation

::: center
:::

[Quelle](http://tinyurl.com/guca8ah)

## Theoretische Differenzen zwischen additiven und multiplikativen Indizes

- Die oben dargestellten additiven Indizes beruhen auf der Annahme, dass Ausprägungen in einer Dimension Nullwerte in einer anderen Dimension ausgleichen können.

- Sie nehmen außerdem an, dass Kombinationen von sehr hohen oder sehr niedrigen Ausprägungen gleichabständig zu anderen Kombinationen sind.

- Wir können aber jede Dimension als *notwendige Bedingung* ansehen, in denen Ausprägungen jenseits von null vorliegen müssen, damit wir in einem Gesamtindex oder einem Gesamttypus Ausprägungen weiter unterscheiden.

- Kombination von hohen Werten können uns außerdem besonders bedeutsam sein.

## Bechdel-Test

Der Bechdel-Test soll messen, ob ein Film nicht einseitig Männer orientiert ist. Er ist es genau dann, wenn:

1.  mindestens zwei Frauen vorkommen, die

2.  miteinander reden und

3.  dieses Gespräch nicht einen Mann zum Gegenstand hat.

::: center
:::

## Personalauswahl

Eine Personalabteilung soll Kandidat:innen nach ihrem Potential für das Unternehmen sortieren. Dazu erfassen sie die Fachkompetenz, die Erfahrung und die Teamfähigkeit der Kanditat:innen in drei Ausprägungen: 0 = nicht vorhanden, 1 = in Ordnung, 2 = exzellent.\
Sie können drei Indizes erstellen: Index 1 ist additiv, Index 2 ist gewichtet-additiv (Gewichte in Klammern) und Index 3 ist multiplikativ.

## Personalauswahl

- Index 1 unterscheidet die ersten vier Kanditat:innen gar nicht, weil sich die Schwächen gegenseitig kompensieren. Kandidat:in 5 & 6 unterscheiden sich in Bezug auf ihre Gesamtpassung nur gering.

- Index 2 bringt Kanditat:in 6, 5 und 1 auf die ersten drei Plätze.

- Index 3 sortiert die ersten drei Kandidat:innen aus und differenziert die letzten drei Kandidat:innen stark aus.

# Typenbildung

##  {#section-2 .unnumbered}

## Typenbildung

Im einfachsten Fall lassen sich Typen aus Ausprägungskombination von zwei Dimensionen oder Eigenschaften bilden. Wir können zum Beispiel eine (sehr) einfache Typologie von Lebensformen wie folgt bilden:

::: center
                  Ein Erwachsener     Zwei Erwachsene   
  --------------- ------------------- ----------------- --
  ohne Kind(er)   Single-Haushalt     Paar-Haushalt     
  mit Kind(ern)   Allein-Erziehende   Kernfamilie       
:::

## Die Welt ist bunt

::: center
:::

[Quelle](https://twitter.com/familyunequal/status/1586809982925815808)

## Managementtypen

:::::: center
:::: minipage
::: center
:::

[Quelle](https://link.springer.com/chapter/10.1007/978-3-658-07768-6_44)
::::

::: minipage
Manchmal sind nicht alle Ausprägungskombinationen gleich wichtig (im Beispiel sind es 81 Kombinationen). In diesem Fall werden die Ausprägungskombinationen auf wenige typische oder theoretisch relevante reduziert.\
Wichtig: Diese Entscheidungen müssen sich bewähren. D.h., wir müssen testen, wie gut diese neu geformten Unterschiede andere Unterschiede erklären können. Es ist ja auch denkbar, dass diese Unterschiede in der sozialen Welt keinerlei Relevanz haben oder Personen sehr variabel agieren und sich daher wenig in ein solches Unterscheidungsschema einpassen.

\
:::
::::::
