## (ohne Titel)

# Unterschiedlichkeit messen {#unterschiedlichkeit-messen .unnumbered}

##  {#section .unnumbered}

## Unterschiede messen

::: center
:::

[Quelle](https://www.splashlearn.com/math-vocabulary/measurements/measurement)

## Unterschiede auf eine Skala bringen: Berufsprestige

::::: center
::: minipage
\
[Quelle](https://d-nb.info/119113590X/34)
:::

::: minipage
[Ebner & Rohrbach-Schmidt (2022)](https://www.degruyter.com/document/doi/10.1515/zfsoz-2021-0026/html) haben eine Skala für das soziale Ansehen von Berufen entwickelt.\
Damit lassen sich Berufe nach ihrem Prestige unterscheiden und anhand einer Skala sortieren (links am Beispiel von Ausbildungsberufen).\
\
\
:::
:::::

## Unterschiede auf eine Skala bringen: Masken

::: center
:::

[Quelle](https://xkcd.com/2367/)

## Problem: Nicht alle Unterschiede sind direkt beobachtbar

::: center
:::

## Faktor, Beobachtung & Fehler

::: center
:::

## Faktor, Beobachtung & Fehler

- Unterschiede der Untersuchungseinheiten führen zu unterschiedlichen Beobachtungen (durch Fragebögen, Experimente, Feldbeobachtugen, Verhaltensdaten, usw.).

- Der Unterschied zwischen latenten und beobachtbaren Eigenschaften liegt darin, wie gut wir von einer (!) Beobachtung der Untersuchungseinheit auf die zugrunde liegende Eigenschaft schließen können.[^1]

- Unterschiede in den Störfaktoren (über Gruppen oder Beobachtungskontexte) führen zu unterschiedlichen Beobachtungen und daher auch zu anderen Einschätzungen über die Ausprägung der zugrunde liegenden Eigenschaft.

## Reminder: Wir wollen systematische Zusammenhänge studieren.

- Unser Ziel ist es, soziale Prozesse besser zu verstehen.

- **Dazu müssen wir verstehen, wie Unterschiede der Eigenschaft A mit Unterschieden der Eigenschaft B zusammenhängen.**

- Aussagen, die solche systematischen Zusammenhänge behaupten, werden als **Hypothesen** bezeichnet.

- Um Hypothesen zu testen zu können, müssen wir die unterschiedlichen Ausprägungen von A und B aber erst erfassen bzw. beobachtbar machen.

## Impulsivität und Verhaltensprobleme

::::: center
::: minipage
\
[Quelle](https://www.frontiersin.org/articles/10.3389/fpsyg.2015.01674/full)
:::

::: minipage
Mütter und Väter sind bessere Informationsquellen über das Verhalten des Kindes als Selbstangaben.\
Mütter und Väter können Impulsivität und Verhaltensprobleme ähnlich gut angeben, unterscheiden sich aber erheblich bei der Frustrationstoleranz.\
\
\
\
:::
:::::

## Alter und Gesundheit

::: center
:::

## Alter und Gesundheit: Empirie

::: center
:::

## Von Hypothesen zu Variablen

Eine Variable ist eine Zusammenfassung aller beobachteten Ausprägungen eines Merkmals.

## Variablenerfassung

::: center
:::

## Variablenerfassung

::: center
:::

## Von Hypothesen zu Variablen

Zur Erstellung einer Variable benötigt man daher:

1.  eine Definition eines Konzepts;

2.  die Angabe, welche Dimensionen das Konzept hat und welche Ausprägungen unterschieden werden sollen;

3.  eine Angabe, auf welche Weise die behaupteten Ausprägungen *beobachtet* werden können.

Der erste Punkt wird häufig *Konzeptspezifikiation* und der zweite und dritte Punkt *Operationalisierung* genannt. Da Konzepte nie beobachtet werden können (sondern nur das, was ein Beobachter für eine Ausprägung eines Merkmals hält), beruht jede Variable auf *Indikatoren*.

[^1]: Der Übergang kann z.T. sehr fließend sein!
