## (ohne Titel)

# Latente Eigenschaften {#latente-eigenschaften .unnumbered}

##  {#section .unnumbered}

## Die Messung latenter Eigenschaften

::: center
:::

## Die Messung latenter Eigenschaften

- Wir können Unterschiede in den Ausprägungen latenter Eigenschaften durch mehrere Beobachtungen erfassen.

- Die zugrunde liegende, latente Eigenschaft führt zu unterschiedlichem Verhalten/Zuständen der Untersuchungseinheiten.

- Die Kombination der unterschiedlichen Verhaltensweisen oder Zustände kann uns einen Rückschluss auf die latente Eigenschaft ermöglichen.

- Wenn wir jeder beobachteten Verhaltensweise oder Zustand einen Zahlenwert zuweisen, können wir für die latente Eigenschaft eine/n Skala/Index erstellen.

## Die Messung latenter Eigenschaften

:::::: columns
:::: column
0.5

::: center
:::
::::

::: column
0.5 Dieses Meßmodell beruht auf wichtigen Annahmen:

1.  Die Beobachtungen werden nur von einem einzigen latenten Faktor beeinflusst.

2.  Da die beobachteten Verhaltensweisen oder Zustände auf einer latenten Eigenschaft beruhen, sollten die Ausprägungen in systematischen Zusammenhang miteinander und zu der latenten Eigenschaft stehen.

3.  Die Störfaktoren sind voneinander unabhängig und treten zufällig auf.
:::
::::::

## Latente Eigenschaften: Misantrophie

::::: columns
::: column
0.3\
[Quelle](https://cdn.clipart.email/f0c8e108edaa7257a31d03c3682427cf_sketch-girls_236-272.jpeg)
:::

::: column
0.7 **Misantrophy Scale**

1.  Humans are by nature basically corrupt.

2.  Both history and current events show that human beings are basically wicked.

3.  Planet earth would be better off if humans would just disappear from it.

4.  Most people are basically good natured.

5.  I am proud to be a member of the human race.

\

       strongly disagree   disagree   no opinion   agree   strongly agree  
  --- ------------------- ---------- ------------ ------- ---------------- --
  1                                                                        
  2                                                                        
  3                                                                        
  4                                                                        
  5                                                                        
:::
:::::

# Auswahl von Indikatoren {#auswahl-von-indikatoren .unnumbered}

##  {#section-1 .unnumbered}

## Auswahl von Indikatoren

Die beobachteten Unterschiede in den Verhaltensweisen oder Zustände der Untersuchungseinheinten (= Indikatoren) müssen mehrere Anforderungen erfüllen, damit eine sinnvolle Erfassung der latenten Eigenschaft erfolgen kann:

1.  Die Indikatoren müssen die volle **Bandbreite** der (theoretisch postulierten) Unterschiede erfassen können.

    1.  Dazu wird in der Regel ein **Indikatorenpool** angelegt, der im Rahmen einer Befragung auch als **Itempool** bezeichnet wird.

    2.  Aus diesem Pool müssen die geeignetsten Indikatoren oder Items **selektiert** werden.

2.  Die beobachteten Unterschiede müssen so **kombinierbar** sein, dass damit jeder Untersuchungseinheit ein spezifischer Wert zugeordnet werden kann und somit alle Untersuchungseinheiten nach ihrer Unterschiedlichkeit sortiert werden können.

## Thurstone-Skalierung

:::::: columns
:::: column
0.3

::: center
\
[Louis Leon Thurstone (1887-1955)](https://www.biografiasyvidas.com/biografia/t/thurstone.htm)
:::
::::

::: column
0.7 Eine Möglichkeit, latente Eigenschaften durch Befragungen oder psychologische Tests zu erfassen, wurde von Louis Leon Thurstone entwickelt.\

Die Methode wird insbesondere für Intelligenztests und die Erfassung von Einstellungen angewandt.\

Sie setzt voraus, dass die Ausprägungen der latenten Eigenschaften eine Hierarchie haben (also mindestens ordinal skaliert sind).
:::
::::::

## Thurstone-Skalierung

1.  Anlage eines großen Itempools, der das gesamte Spektrum aller Reaktionen/Einstellungen/Verhaltensweisen enthalten soll, das theoretisch erfasst werden soll.

2.  Die Items werden Expert:innen zum bewerten (engl.: *rating*) vorgelegt. Die Bewertungen orientieren sich an der Hierarchie der Ausprägungen der latenten Eigenschaft.

3.  Items, bei denen Uneinigkeit zwischen den Expert:innen besteht, werden ausgechlossen.

4.  Jedes Item erhält den Durchschnittsbewertung aller Expert:innen. Dadurch lassen sich die Items in eine Ordnung bringen, die die "Position" des Items in der Hierarchie der latenten Eigenschaft darstellt.

5.  Die Items werden Probanten vorgelegt. Als Antwortkategorien sind nur binäre Kategorien zugelassen: ja (= 1)/nein (= 0); Aufgabe gelöst (= 1)/nicht gelöst (= 0); Reaktion gezeigt (= 1) / nicht gezeigt (= 0).

6.  Für jeden Probant wird die Summe aus allen ja/gelöst/Reaktion gezeigt (= 1) Itemscores gebildet. Mit diesem Wert lassen sich die Personen nach ihrer Ausprägung der latenten Eigenschaft unterscheiden.

## Thurstone-Skalierung

::: center
:::

## Thurstone-Skalierung

Skala für die Kontaktsituation in Wohnsiedlungen (durchschnittliche Expertenwertung von -5 bis +5 in Klammern):\

1.  Ich komme mir in dieser Siedlung oft vor wie ein Fremder. ($-2,00$)

2.  Keinem Menschen in der Nachbarschaft würde es auffallen, wenn mir etwas zustieße. ($-3,05$)

3.  Hier in der Siedlung haben die Menschen keine Geheimnisse voreinander. ($+3,30$)

4.  Ich habe oft den Eindruck, dass sich die Menschen in meinem Wohnbezirk nur flüchtig kennen. ($-0,53$)

5.  Ich kenne kaum jemanden in meinem Wohnbezirk, mit dem ich über private Dinge reden könnte. ( $-0,33$)

6.  In diesem Wohnbezirk ist es kaum möglich, sich auch nur für kurze Zeit von den anderen zurückzuziehen. ( $+1,79$)

7.  Ich kenne hier in der Nachbarschaft fast jeden mit Namen. ($+0,90$)

## Guttman-Skalierung

:::::: columns
:::: column
0.3

::: center
\
[Louis E. Guttman (1916-1987)](https://doritalt80.wixsite.com/ftas)
:::
::::

::: column
0.7 Ein weiteres Verfahren zur Erfassung latenter Eigenschaften wurde von Louis E. Guttman entwickelt.\

Diese Art der Skalierung setzt voraus, dass die latente Eigenschaft Ausprägungen (in überschauberer Anzahl) hat, die streng hierarchisch geordnet sind.
:::
::::::

## Guttman-Skalierung

Grundlegende Idee:

1.  Entwickle eine Liste von Items, die alle Ausprägungen des Merkmals erfassen. Die Items müssen sich streng nach der Hierarchie der Ausprägungen sortieren lassen (z.B.: von nicht hilfsbedürftig bis stark hilfsbedürftig) und dürfen sich nicht überschneiden.

2.  Lege die Liste Personen vor, die binär reagieren müssen: z.B.: ablehnen oder zustimmen / lösen oder nicht lösen.

3.  Die Anzahl aller positiven Reaktionen pro Person bildet eine Rangfolge, die die Ausprägung der latenten Eigenschaft wiedergibt.

## Guttman-Skalierung: Antisemitismus

Würden Sie es begrüßen, wenn

1.  Juden Deutschland besuchen.

2.  Juden sich in Deutschland niederlassen.

3.  Sie einen Juden als Arbeitskollegen haben.

4.  Sie einen Juden als Freund haben.

5.  Sie einen Juden heiraten würden.

## Guttman-Skalierung: Grad der körperlichen Behinderung

Die Person kann nicht ohne Hilfe:

1.  baden.

2.  außer Haus laufen.

3.  im Haus laufen.

4.  sich anziehen.

5.  aus dem Bett aufstehen.

6.  sitzen oder stehen.

7.  auf die Toilette gehen.

8.  die Hände und das Gesicht waschen.

9.  essen.

## Unterschiede zwischen Guttman und Thurstone Skalierungen

- Positive und negative Reaktionen können sich bei einer Thurstone-Skala gegenseitig aufheben, aber nicht bei einer Guttman-Skala.

- Bei der Guttman-Skala gibt es (offiziell) keine Expert:innen, die für die Vorselektion sorgen.

- Guttman-Skalen sind praktisch auf Eigenschaften mit überschaubaren Ausprägungen begrenzt.

## Likert-Skalierung

:::::: columns
:::: column
0.3

::: center
\
[Rensis Likert (1903-1981)](https://doritalt80.wixsite.com/ftas)
:::
::::

::: column
0.7 Die von Louis Thurstone oder Louis Guttman entwickelten Skalierungen nutzen die Unterschiedlichkeit der Items (über Scores oder ihre Position in einer Ausprägungshierachie) um Unterschiede der Ausprägungen zu erfassen. Das ist allerdings nicht immer praktikabel. Thurstone-Skalierungen können darüber hinaus sehr aufwändig und teuer sein.\

Rensis Likert entwickelte eine Alternative, die besonders (aber nicht nur!) über die Antwortkategorien der Items die Unterschiedlichkeit von latenten Ausprägungen erfassen soll.

Diese Art der Skalierung setzt voraus, dass Personen in der Lage sind, sich durch ihre Reaktionen konsitent in Bezug auf eine Eigenschaft zu positionieren.
:::
::::::

## Likert-Skalierung

Grundlegende Idee:

1.  Entwickle eine Liste von Items, die Variationen oder Aspekte des zugrunde liegenden Merkmals darstellen.

2.  Lege die Liste der Items Personen vor, die auf die Items mit unterschiedlichen Graden positiv, neutral oder negativ reagieren können.

3.  Personen mit einer Ausprägung im unteren Bereich der Eigenschaft sollten daher sehr oft negativ auf die Items reagieren und Personen mit einer hohen Ausprägung der Eigenschaft sollten sehr oft positiv reagieren.

4.  Die Summe aus allen Reaktionen ist der Meßwert für jede Person.

## Likert-Skalierung

:::::: columns
:::: column
0.5

::: center
:::
::::

::: column
0.5

- Die verschiedenen Items rufen unterschiedliche Reaktionen hervor.

- Die Summe der unterschiedlichen Reaktionen ist die Messung für die zugrunde liegende, latente Ausprägung.

- Items für Likert-Skalen müssen daher stets unterschiedliche Reaktion hervorrufen. Items, die in hohem Maße eine Form der Reaktion hervorrufen, sind ungeeignet.
:::
::::::

## Dimensionen beruflicher Selbstregulation

:::::: center
:::: minipage
::: center
:::
::::

::: minipage
- Likert-Skalierungen eignen sich zur Messung von ein- und mehrdimensionalen Konstrukten.

- Bei mehrdimensionalen Konstrukten wird pro Dimension eine eigene Likert-Skala mit eigenen Items gebildet.
:::
::::::

## Die Messung der Ausprägungen einer Dimension

:::::: center
:::: minipage
::: center
:::
::::

::: minipage
- Befragten werden für die Messung der Unterdimension *Bedeutsamkeit der Arbeit* folgende Aussagen vorgelegt:

  - Die Arbeit ist für mich der wichtigste Lebensinhalt.

  - Die Arbeit ist mein Ein und Alles.

  - Ich brauche die Arbeit wie die Luft zum Atmen.

- Die Befragten konnten Angaben auf einer 5er-Skala machen: 1 "trifft gar nicht zu"; 2 "trifft eher nicht zu"; 3 "teils/teils"; 4 "trifft eher zu"; 5 "trifft völlig zu".
:::
::::::

## Berufliche Selbstregulation

::: center
:::

## Berufliche Selbstregulation

::: center
:::
