---
title: "Statistical Critique 2: Exploring p-values"
author: "Your name here!"
format: html
self-contained: true
editor: visual
---

```{r}
#| label: data-load

library(tidyverse)
library(moderndive)
library(broom)

# Reference the R package you data live inside, since you will need to load that package in!
# Package for your data:

```

# Part One: Revisiting the Midterm Project

For the first part of this critique, you are going to revisit the model you selected for your Midterm Project.

## Visualizations

```{r}
#| label: project-plots
# In the code chunk below, copy-and-paste the plots you created in your Midterm Project.

```

## Model Justification

<!-- Justify (in 2-3 sentences) why you chose this model! -->

# Part Two: Using a p-value Instead

```{r}
#| label: obtain-p-values
# Step 1: fit the most complex regression model
# Step 2: run an ANOVA to obtain p-values

```

**Based on the p-value(s) you obtained from the ANOVA, what model is the "best" model?**

# Part Three: Learning More about Misuses of $p$-values


