---
title: "Week 10 -- Two-Way ANOVA"
format: docx 
editor: visual
---

::: callout-warning
## Answers in different color text

It is **really** helpful for me if you make your answers in a different color, so I can easily pick them out!
:::

**In a completely randomized design (CRD), how are the treatments assigned?**

</br> </br>

**What is a nuisance factor?**

</br> </br>

**Why would you want to block based on a nuisance factor?**

</br> </br>

**In the example of fertilizer application on wheat fields, why is each fertilizer rate applied only once within each field?**

</br> </br>

**In a randomized complete block design (RCBD), how are the treatments assigned?**

</br> </br>

**Why should you expect for a "good" blocking variable to have a small p-value in the ANOVA table?**

</br> </br>

**What can you say about the blocking variable if its p-value (from the ANOVA table) is large?**

</br> </br>

**What happens to the error (residual) sum of squares if you ignore a blocking variable? Why is this bad?**

</br> </br>

**Suppose you're part of a research team investigating the efficacy of a newly designed [beta blocker](https://en.wikipedia.org/wiki/Beta_blocker). What are two variables you believe would be important to block on?**

</br> </br>

**How are treatments assigned in a Latin square design?**
