---
title: "Your Title Goes Here! Make it fun!"
author: "Your Name Here!"
format: 
  html:
    code-tools: true
editor: visual
embed-resources: true
execute: 
  echo: false
  message: false
  warning: false
---

```{r}
#| label: data

library(tidyverse)
library(broom)
library(ggridges)

# This is where you will load in your data! 
# Reference the R package you data live in, since you will need to load that package in!


```

## Introduction

## Methods

### Variables

### Visualizations

```{r}
#| label: density-ridge-plots
#| fig-align: center
#| layout-nrow: 1

## Code to make your density ridge plots goes here! 
## You should have two total plots!
## Don't forget to choose nice axis labels!


```

<!-- Descriptions of visualizations go here! -->


### Statistical Methods

<!-- What model did you choose and why? -->


# Findings

## One-Way ANOVA of <RESPONSE VARIABLE> and <EXPLANATORY VARIABLE>

```{r}
#| label: one-way-anova-var1 

## Code to fit your one-way ANOVA model for variable 1


## Code to get your p-value for your ANOVA


```

## One-Way ANOVA of <RESPONSE VARIABLE> and <EXPLANATORY VARIABLE>

```{r}
#| label: one-way-anova-var2 

## Code to fit your one-way ANOVA model for variable 2


## Code to get your p-value for your ANOVA


```

# Discussion

<!-- 1. Hypothesis test conclusions -->


<!-- 2. Possible explanation why results were observed -->


<!-- 3. How trustworthy are your findings -->


# Conclusion

<!-- 1. Connect findings back to original research questions -->

<!-- 2. How does the study design influence what can / cannot be said about the relationships you found in your analysis? -->

<!-- 3. How does the study design influence what population you can / cannot infer your results onto? -->

