{
  "hash": "0dad0e4fa8897add41cbe2bca6829e04",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Gute Vergleiche: Vergleichsgegenstände -- Akt II\"\nslide-level: 2   # <— hier trennt Quarto an \"##\"\nlightbox: true\ncss: global.css\nformat: \n  revealjs:\n    fig-format: svg\n    fig-width: 16\n    fig-asp: 0.618\n    out-width: \"70%\"\n    fig-align: center\n    width: 1400\n    height: 1050\n    auto-stretch: false\n    theme: style.scss\n    margin: 0.01\n    slideNumber: true\n    mermaid: \n      theme: neutral\n      look: classic\n      layout: elk\neditor: source\ntbl-cap-location: bottom\nexecute: \n  echo: false\n  message: false\n  warning: false\n---\n\n\n\n::: {.cell}\n\n:::\n\n\n# Differenzen entlang von Verteilungen\n\n## Jenseits des Mittelwerts\n\n- Manchmal liegen die \"interessanten Unterschiede\" zwischen Gruppen nicht in der Mitte der Verteilungen sondern ganz oben oder unten. \n\n- Mittelwerte oder Varianzen können diese Unterschiedlichkeit nur sehr begrenzt erfassen. \n\n- Es lohnt sich daher, verschiedene Stellen der Verteilung zu analysieren. Dazu können wir Verteilungen in beliebig viele, gleich große[^1] Teile zerlegen. \n\n[^1]: Gleich groß bedeutet hier, eine gleiche Anzahl von Beobachtungen -- aber nicht gleich viel \"Fläche\" in einem Koordinatensystem.\n\n## Begrifflichkeiten {.midi}\n\n\n::: {.columns}\n::: {.column}\n| Bezeichnung       \t| Anzahl gleich großer Teile \t| Abkürzung       \t|\n|-------------------\t|----------------------------\t|-----------------\t|\n| Quartil           \t| 4                          \t| $Q1 \\dots Q4$   \t|\n| Dezil             \t| 10                         \t| $D1 \\dots D10$  \t|\n| Quantil/Perzentil \t| 100                        \t| $P1  \\dots P99$ \t|\n\n:::\n\n::: {.column}\n\n- Quartile und Perzentile können synonym benutzt werden. Der Wertebereich von Quantilen liegt zwischen 0.01 und 0.99, während er bei Perzentilen zwischen 1 und 99 liegt. \n\n- Das 50. Perzentil ist der Median. \n\n- Mit Quartilen und Dezilen werden typischerweise die Abschnitte einer Verteilung bezeichnet. \n\n- Quantile und Perzentile bezeichnen aber immer die Grenze eines Abschnitts. Es ist daher der Wert einer Verteilung, der einen neuen Abschnitt nach oben hin definiert. \n\n:::\n:::\n\n\n## Quartile und Boxplots \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](17-VergleichsgegenstaendeII_files/figure-revealjs/unnamed-chunk-2-1.svg)\n:::\n:::\n\n\n\n## Dezile und Perzentile\n\n::: {.cell}\n::: {.cell-output-display}\n![](17-VergleichsgegenstaendeII_files/figure-revealjs/unnamed-chunk-3-1.svg)\n:::\n:::\n\n\n## Vertiefung: Wie kummulative Häufigkeiten und Perzentile zusammenhängen\n\nWir können bei ordinalen oder metrischen Ausprägungen die relativen Häufigkeiten laufend aufsummieren und erhalten auf diese Art \"kummulative Häufigkeiten\". Kummulative Häufigkeiten geben an, wie viel Prozent der Beobachtungen einen bestimmten Wert **oder** einen kleineren Wert haben. \n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Beilegung von Meinungsverschiedenheiten (Streiten/laut werden)\n\n| Wert|Kategorie |    n|Rel. Häufigkeit |Kum. Häufigkeit |\n|----:|:---------|----:|:---------------|:---------------|\n|    1|Nie       | 4827|28,0%           |28,0%           |\n|    2|Selten    | 7136|41,4%           |69,4%           |\n|    3|Manchmal  | 3858|22,4%           |91,8%           |\n|    4|Oft       | 1241|7,2%            |99,0%           |\n|    5|Sehr oft  |  181|1,0%            |100,0%          |\n\n\n:::\n:::\n\n\n\n## Vertiefung: Wie kummulative Häufigkeiten und Perzentile zusammenhängen\n\n\n::: {.columns}\n\n::: {.column}\n\nJede stetige Verteilung lässt sich mit einer Verteilungsfunktion (unten) und einer kummulativen Verteilungsfuntion (oben) darstellen. Perzentile/Quantile sind die Werte, die kummulative Häufigkeiten in beiden Verteilungen abtrennen. \n\n:::\n\n::: {.column}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](17-VergleichsgegenstaendeII_files/figure-revealjs/unnamed-chunk-5-1.svg)\n:::\n:::\n\n\n:::\n:::\n\n## Vermögensverteilung in Deutschland (2023)\n\n::: {.r-fit-text}\n| Verteilung von Brutto- und Nettovermögen \t| Bruttovermögen (€) \t| Nettovermögen (€) \t|\n|------------------------------------------\t|--------------------\t|-------------------\t|\n| 5. Perzentil                             \t| 900                \t| −800              \t|\n| 10. Perzentil                            \t| 2.900              \t| 800               \t|\n| 20. Perzentil                            \t| 10.100             \t| 7.100             \t|\n| 30. perzentil                            \t| 22.300             \t| 19.100            \t|\n| 40. Perzentil                            \t| 55.200             \t| 49.300            \t|\n| 50. Perzentil                            \t| 125.300            \t| 103.200           \t|\n| 60. Perzentil                            \t| 237.000            \t| 196.100           \t|\n| 70. Perzentil                            \t| 366.900            \t| 326.200           \t|\n| 80. Perzentil                            \t| 520.400            \t| 473.500           \t|\n| 90. Perzentil                            \t| 856.900            \t| 779.500           \t|\n| 95. Perzentil                            \t| 1.338.500          \t| 1.227.900         \t|\n::: \n\n## Vermögensverteilung in Ost- und Westdeutschland \n\n::: {.r-fit-text}\n|                       \t|    West    \t|     Ost    \t|\n|:---------------------:\t|:----------:\t|:----------:\t|\n|                       \t|    2012    \t|    2012    \t|\n| Mittelwert            \t|     93 790 \t|     41 138 \t|\n| Median                \t|     21 200 \t|      8 080 \t|\n| 90. Perzentil         \t|    239 300 \t|    111 580 \t|\n| 95. Perzentil         \t|    363 980 \t|    171 359 \t|\n| 99. Perzentil         \t|    876 050 \t|    399 820 \t|\n|                       \t|            \t|            \t|\n|                       \t|            \t|            \t|\n|                       \t|            \t|            \t|\n| Negatives oder kein Vermögen in %    \t| 26,9       \t| 30,8       \t|\n| 90/50-Dezilverhältnis \t| 11,30      \t| 13,81      \t|\n:::\n\n## Die Daten-Spielwiese (ALLBUS 2018)\n\n<iframe width=\"100%\" height=\"100%\" src=\"https://019d8719-55fd-c4ab-9a3f-8a43cc60bba4.share.connect.posit.cloud\" ></iframe>\n\n# Differenzen von einzelnen Ausprägungen, Ereignissen, Kategorien\n\n## Wahrscheinlichkeiten, Chancen, Risiko\n\n-   Wir interessieren uns oft dafür, wie wahrscheinlich es ist, dass Personen zu einer bestimmten Gruppe gehören (Mieter vs. Eigentümer; Studium vs. Ausbildung; genesen vs. nicht genesen).\n\n-   Soziale Prozesse beeinflussen diese Wahrscheinlichkeiten, sodass es zu Differenzen über verschiedene Gruppen kommt.\n\n-   In vielen Fällen ist es sinnvoll, diese Differenzen als Wahrscheinlichkeiten auszudrücken, allerdings sind wir oft auch an Veränderungen in den *Verhältnissen zwischen Gruppen* interessiert.\n\n## Notationen\n\n| Abkürzung | Bedeutung |\n|:---|:---|\n| P(Y) | Wahrscheinlichkeit von Y |\n| $P(Y|X)$ | Wahrscheinlichkeit von Y unter der Bedingung, dass X vorliegt |\n| $RR_{Y}$ | Risikoverhältnis (oder Risk Ratio) einer (Referenz)Gruppe auf Y gegenüber einer anderen Gruppe |\n| $Odd_Y$ | Chance auf Y (im Gegensatz zu \"Nicht Y\") |\n| $Odd_{Y|X}$ | Chance auf Y unter der Bedingung, dass X vorliegt |\n| $OR_{Y}$ | Chancenverhältnis von Y von Gruppe A in Referenz auf Gruppe B |\n\n## Alleinerziehende\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Relative Anzahl von Alleinerziehenden pro Anzahl von Kindern im Haushalt\n\n|nkidsliv_c         | Hat keine/n Partner/in |Hat Partner/in |\n|:------------------|:-----------------------|:--------------|\n|1                  |544 (9,1%)              |5420 (90,9%)   |\n|2                  |350 (5,0%)              |6704 (95,0%)   |\n|3                  |74 (4,0%)               |1795 (96,0%)   |\n|4 or more children |24 (4,4%)               |521 (95,6%)    |\n\n\n:::\n:::\n\n\nDie unbedingte Wahrscheinlichkeit, als Elternteil alleinerziehend zu sein liegt bei 6.4%.\n\n## \"Risiken\" für Alleinerziehnde: Region\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](17-VergleichsgegenstaendeII_files/figure-revealjs/unnamed-chunk-7-1.svg)\n:::\n:::\n\n\n## \"Risiken\" für Alleinerziehnde: Geschlecht\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](17-VergleichsgegenstaendeII_files/figure-revealjs/unnamed-chunk-8-1.svg)\n:::\n:::\n\n\n## \"Risiken\" für Alleinerziehnde: Bildungsabschluss\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](17-VergleichsgegenstaendeII_files/figure-revealjs/unnamed-chunk-9-1.svg)\n:::\n:::\n\n\n## Odds & Relatives Risiko\n\n$X_0$ ist die \"Referenzgruppe\" - d.h., die Gruppe auf der wir eine andere Gruppe mit einer anderen Ausprägung von $X$ vergleichen ($X = x$).\n\n$$RR_{Y} = \\dfrac{P(Y| X = x)}{P(Y | X_0)}$$\n\n$$Odd_Y = \\dfrac{P(Y)}{ 1 - P(Y)}$$\n\n$$OR_{Y} = \\dfrac{Odd_{Y| X = x}}{Odd_{Y| X_0}}$$\n\n\n## Odds & Relatives Risiko\n\n:::::::: columns\n::: column\n| Gruppe A | Gruppe B |\n|:--------:|:--------:|\n|    \\+    |    \\+    |\n|    \\+    |    \\+    |\n|    \\-    |    \\+    |\n|    \\-    |    \\+    |\n|    \\-    |    \\-    |\n|    \\-    |    \\-    |\n|    \\-    |    \\-    |\n|    \\-    |    \\-    |\n|    \\-    |    \\-    |\n|    \\-    |    \\-    |\n\n: Positive vs. negative Ereignisse innerhalb Gruppe A und B. \n:::\n\n:::::: column\n::: callout-note\n## Wahrscheinlichkeiten\n\nGruppe A: $P(+) = 0.2$\n\nGruppe B: $P(+) = 0.4$\n\nAusgedrückt als bedingte Wahrscheinlichkeiten $P(+|A) = 0.2 \\, \\& \\, P(+|B) = 0.4$\n:::\n\n::: callout-note\n## Odds (Chancen)\n\n$Odd_{+|A} = \\dfrac{0.2}{1 - 0.2} = \\dfrac{1}{4}$ = 1:4\n\n$Odd_{+|B} = \\dfrac{0.4}{1 - 0.4} = \\dfrac{2}{3} =$ 2:3\n:::\n\n::: callout-note\n## Odds Ratio & Relatives Risiko\n\n$OR_{+} = \\dfrac{2/3}{1/4}$ = 2.6667\n\n$RR_+ = \\dfrac{0.4}{0.2} = 2$\n:::\n::::::\n::::::::\n\n## Das geschlechtsspezifische Risiko, alleinerziehend zu sein\n\nAusgehend von den geschlechtsspezifischen Wahrscheinlichkeiten alleinerziehend zu sein, können wir Odds, Odds Ratios und Relative Risiken berechnen. \n\n:::::::: columns\n:::: column\n\n::: {.r-fit-text}\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|sex_c |Alleinerziehend |Nicht alleinerziehend |\n|:-----|:---------------|:---------------------|\n|Mann  |242 (1,6%)      |14585 (98,4%)         |\n|Frau  |748 (4,0%)      |18155 (96,0%)         |\n\n\n:::\n:::\n\n\n::: \n::::\n\n:::: column\n$$Odd_F = \\dfrac{4.0}{96.0} = 0.042 $$ \n\n$$Odd_M = \\dfrac{1.6}{98.4} = 0.016$$ \n\n$$ OR_{F/M} = \\dfrac{0.042}{0.016} = 2.625 $$ \n\n$$ RR_{F/M} = \\dfrac{4.0}{1.6} = 2.5 $$ \n:::: \n::::::::\n\n## Der Unterschied zwischen Odds Ratios und Relativen Risiken\n\nDer Unterschied zwischen OR und RR ist kein Zahlenspielchen sondern eine Frage der Wissenschaftskommunikation. Rein technisch müssen Sie auf zwei Dinge achten, die am einfachsten im Rahmen eines klassichen Experiments deutlich werden. \n\n\n\n|                \t| Dinge passieren \t| Dinge passieren nicht \t|\n|----------------\t|:---------------:\t|:---------------------:\t|\n| Versuchsgruppe \t|      $N_a$      \t|         $N_b$         \t|\n| Kontrollgruppe \t|      $N_c$      \t|         $N_d$         \t|\n\n## Der Unterschied zwischen Odds Ratios und Relativen Risiken\n\n\nBei RR berechnen wir eine Relation von Wahrscheinlichkeiten, dass Dinge passieren in Bezug auf die Wahrscheinlichkeit auf alle Ereignisse (= Dinge passieren + Dinge passieren **nicht**): \n$$ RR = \\dfrac{N_a}{N_a + N_b} / \\dfrac{N_c}{N_c + N_d} $$\n\nBei Odds Ratios berechnen wir für jede Gruppe die Relation, dass Dinge passieren oder nicht[^1] und setzen diese Relation dann zueinander ins Verhältnis: \n\n$$ OR = \\dfrac{N_a}{N_b} / \\dfrac{N_c}{N_d} $$\n\n\n\n[^1]: Für die Expert:innen: ORs werden mit P(Dinge passieren)/P(Dinge passieren nicht) berechnet. Wir können hier aber das N rauskürzen. \n\n## Der Unterschied zwischen Odds Ratios und Relativen Risiken {.midi}\n\n:::::::: columns\n:::: column\n\nRR und OR sind nahezu identisch, wenn die Wahrscheinlichkeit, dass in der \"Kontrollgruppe\" Dinge **passieren** gering ist (=\"Baseline Risk\").  Je höher diese Wahrscheinlichkeit ist, desto stärker divergieren OR und RR.  \n\nFormal besteht zwischen RR und OR folgendes Verhältnis (mit $P_{BL}$ als Baseline Risiko): \n\n$$ RR = \\frac{OR}{1 - P_{BL} + OR \\cdot P_{BL}} $$ \n\n$$ OR = \\frac{RR \\cdot (1 - P_{BL})}{1 - P_{BL} \\cdot RR} $$\n\n::::\n\n:::: column\n\n::: {.cell}\n::: {.cell-output-display}\n![](17-VergleichsgegenstaendeII_files/figure-revealjs/unnamed-chunk-11-1.svg)\n:::\n:::\n\n::::\n::::::::\n\n## Sind Männer konservativer? \n\nBehauptung: Kinder unter 6 Jahren leiden, wenn die Mutter erwerbstätig ist. \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|                          | Männer (%)| Männer kum. (%)| Frauen (%)| Frauen kum. (%)|\n|:-------------------------|----------:|---------------:|----------:|---------------:|\n|Stimme überhaupt nicht zu |       25.5|            25.5|       39.8|            39.8|\n|Stimme eher nicht zu      |       32.4|            57.8|       32.5|            72.4|\n|Weder noch                |       18.9|            76.8|       14.2|            86.6|\n|Stimme eher zu            |       18.3|            95.1|       10.5|            97.1|\n|Stimme voll zu            |        4.9|           100.0|        2.9|           100.0|\n\n\n:::\n:::\n\n\n## Sind Männer konservativer? \n\nWir setzen die Frauen  als \"Kontroll-/Referenzgruppe\" und nehmen \"stimme eher zu\" und \"stimme voll zu\" als \"Ereignis *Zustimmung*\". Dann können wir berechnen: \n\n$$RR = \\frac{23.2}{13.4} = 1.73$$  Das \"Risiko\" auf diese Frage zuzustimmen ist bei Männern um das 1.7-fache höher. \n\n$$OR = \\frac{23.2}{76.8} / \\frac{13.4}{86.6} = 1.96 $$  Die Chance, dass ein Mann zustimmt anstatt \"nicht zustimmt\", ist um das 1.96-fache höher. \n",
    "supporting": [
      "17-VergleichsgegenstaendeII_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}