{
  "hash": "bcb117d427c7ca489c4921f33bd7ae8b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Introduction to Multiple Linear Regression\"\nformat: \n  revealjs:\n    theme: style.scss\neditor: source\n---\n\n\n\n\n\n# Lab 3\n\n## A Grading Reminder\n\n<br>\n\n:::::::: columns\n:::: {.column width=\"47%\"}\n::: {style=\"font-size: 1.25em;\"}\n\"Complete\" = Satisfactory\n:::\n\n<br>\n\nYour group obtained a \"Success\" on **every** question\n::::\n\n::: {.column width=\"5%\"}\n:::\n\n:::: {.column width=\"47%\"}\n::: {style=\"font-size: 1.25em;\"}\n\"Incomplete\" = Growing\n:::\n\n<br>\n\nYour group received a \"Growing\" on *at least one* question\n::::\n::::::::\n\n## Common Mistakes\n\n:::: small\n::: incremental\n-   **Categorical variables in R (Q2)**\n    -   What data types does R use to store categorical variables? Integers? Characters? Doubles? Factors? Dates?\n    -   The output of `glimpse()` can help!\n-   **Comparing distributions between groups (Q9)**\n    -   Were trout observed in every channel type in both sections of forest?\n    -   Does every group have a unimodal distribution?\n    -   How different are the centers and spread of the distributions?\n-   **Comparing means to distributions (Q12)**\n    -   Are the means you obtained close to the peaks of the distributions? \n    -   Why might that not be the case for some distributions? \n:::\n::::\n\n## Making a Duplicate of Your Group's Lab 3 Project\n\n::: {.small}\n1. Log in to [Posit Cloud](https://posit.cloud/)\n2. Open your Weeks 2-3 Group Workspace\n3. Find Lab 3\n:::\n\n![](images/find-lab.png){fig-alt=\"A screenshot of a group's Lab 2 project in their group workspace. There is a purple box around an icon with two boxes that has a 'plus' (+) symbol in the middle.\"}\n\n::: columns\n::: {.column width=\"40%\"}\n::: {.small}\n4. Make a personal copy of your group's Lab 3\n:::\n:::\n\n::: {.column width=\"5%\"}\n:::\n\n::: {.column width=\"55%\"}\n![](images/make-a-copy.png){width=\"50%\" fig-alt=\"A screenshot of the pop-up that appears when you click on the 'Make a copy' icon next to the Lab 2 project.\"}\n:::\n:::\n\n::: {.small}\n::: {.callout-important}\n# Every member must have their own copy of the lab! No one works in the original document.\n:::\n:::\n\n## Completing Revisions\n\nLab 3 revisions are due by Wednesday, May 7.\n\n::: small\n1.  Read comments on Canvas\n2.  Copy your group's lab assignment\n3.  Complete your revisions\n4.  Render your revised Lab 3\n5.  Download your revised HTML\n6.  Submit your revisions to the [original Lab 3]{.underline} assignment\n:::\n\n:::: callout-warning\n# Reflections\n\n::: small\nRevisions are required to be accompanied with reflections on what you learned\nwhile completing your revisions. These are expected to be written in your Lab 3\nQuarto file (next to the problems you revised). \n:::\n::::\n\n# Midterm Project Week\n\n## Plan for Today\n\n1.  Review different types of multiple linear regression models\n\n2.  Complete an activity on sample selection\n\n3.  Start Midterm Project write-up\n\n## Plan for Wednesday\n\n**No lab** -- focus on getting **all** the coding accomplished for the Midterm Project\n\n## Draft Due by Sunday\n\nTo get everyone feedback on their drafts in a timely manner, the first drafts are due by Sunday.\n\n::: callout-caution\n# Deadline Extension\n\nA deadline extension [**is**]{.underline} permitted for the first draft. \nDeadline extensions [**are not**]{.underline} permitted for the final version\n(due next week).\n:::\n\n## Deadlines Throughout the Week\n\nTo try and keep everyone on track for getting the Midterm Project draft \ncompleted by Sunday, I've made some \"check point\" assignments throughout the \nweek. \n\n- Introduction (due Tuesday)\n- Methods & Results (due Thursday)\n- Discussion & Conclusion (due Sunday)\n\n# Multiple Linear Regression\n\n##  Before...\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week5-day1_files/figure-revealjs/old-slr-1.png){width=960}\n:::\n:::\n\n\n\n##  Now...\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week5-day1_files/figure-revealjs/two-mlr-1.png){width=960}\n:::\n:::\n\n\n\n##  {background-color=\"#E4E4E4\"}\n\n</br> </br>\n\n<center>\n\n::: {style=\"font-size: 6em; color: #000000;\"}\nHow?\n:::\n\n</center>\n\n## Offsets!\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nsmoke_lm <- lm(weight ~ weeks * habit, data = ncbirths)\n\nget_regression_table(smoke_lm)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  term              estimate std_error\n  <chr>                <dbl>     <dbl>\n1 intercept           -5.94      0.484\n2 weeks                0.341     0.013\n3 habit: smoker       -1.86      1.63 \n4 weeks:habitsmoker    0.039     0.042\n```\n\n\n:::\n:::\n\n\n\n::: callout-note\n# Interaction Model\n\nThe \\* means the variables are interacting!\n:::\n\n## Estimated Regression Equations\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  term              estimate std_error\n  <chr>                <dbl>     <dbl>\n1 intercept           -5.94      0.484\n2 weeks                0.341     0.013\n3 habit: smoker       -1.86      1.63 \n4 weeks:habitsmoker    0.039     0.042\n```\n\n\n:::\n:::\n\n\n\n::: {style=\"font-size: 1.1em; color: #0F4C81;\"}\nWhat is the regression equation for non-smoker mothers?\n:::\n\n. . .\n\n::: {style=\"font-size: 1.1em; color: #0F4C81;\"}\nWhat is the regression equation for smoker mothers?\n:::\n\n##  {background-color=\"#D4D4D4\"}\n\n::: {style=\"font-size: 2em; color: #000000;\"}\nWould you say that these two groups have different regression lines?\n:::\n\n. . .\n\n::: {style=\"font-size: 2em; color: #000000;\"}\nWhat would the principle of parsimony say?\n:::\n\n\n\n##  When investigating if a relationship differs...\n\n::: {style=\"font-size: 1.25em; color: #000000;\"}\nAlways start with the \"interaction\" / different slopes model.\n:::\n\n. . .\n\n::: {style=\"font-size: 1.25em; color: #b76352;\"}\nIf the slopes look different, you're done!\n:::\n\n. . .\n\n::: {style=\"font-size: 1.25em; color: #0F4C81;\"}\nIf the slopes look similar, then fit the \"additive\" (parallel slopes) model.\n:::\n\n## \n\n::: {style=\"font-size: 2em; color: #000000;\"}\nDifferent Enough?\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week5-day1_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n\n##  What if they're not very different?\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](week5-day1_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n## Parallel Slopes\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"false\"}\nlm(average_sat_math ~ perc_disadvan + size, \n   data = MA_schools)\n```\n:::\n\n\n\n</br>\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  term          estimate std_error\n  <chr>            <dbl>     <dbl>\n1 intercept       588.       7.61 \n2 perc_disadvan    -2.78     0.106\n3 size: medium    -11.9      7.54 \n4 size: large      -6.36     6.92 \n```\n\n\n:::\n:::\n\n\n\n. . .\n\n::: {.callout-warning}\n# What group is the baseline group?\n:::\n\n##  Group equations -- Baseline\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  term          estimate std_error\n  <chr>            <dbl>     <dbl>\n1 intercept       588.       7.61 \n2 perc_disadvan    -2.78     0.106\n3 size: medium    -11.9      7.54 \n4 size: large      -6.36     6.92 \n```\n\n\n:::\n:::\n\n\n\n. . .\n\n$$\\widehat{SAT}_{small} = 588 - 2.78 \\times \\text{percent disadvantaged}$$\n\n##  Group equations -- Offsets\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  term          estimate std_error\n  <chr>            <dbl>     <dbl>\n1 intercept       588.       7.61 \n2 perc_disadvan    -2.78     0.106\n3 size: medium    -11.9      7.54 \n4 size: large      -6.36     6.92 \n```\n\n\n:::\n:::\n\n\n\n. . .\n\n::: small\n$$\\widehat{SAT}_{medium} = (588 - 11.9) - 2.78 \\times \\text{percent disadvan}$$\n:::\n\n::: small\n$$\\widehat{SAT}_{medium} = 576.1 - 2.78 \\times \\text{percent disadvan}$$\n:::\n\n. . .\n\n::: small\n$$\\widehat{SAT}_{large} = (588 - 6.36) - 2.78 \\times \\text{percent disadvan}$$\n:::\n\n::: small\n$$\\widehat{SAT}_{large} = 581.64 - 2.78 \\times \\text{percent disadvan}$$\n:::\n\n# Sample Selection Activity\n\n## Inclusion Criteria\n\n::: {.small}\n> Potential research subjects must meet certain criteria, defined by the\n> researchers, to participate in a study. Inclusion criteria define requirements\n> for inclusion in the study (e.g., a target age range or social group), while\n> exclusion criteria are reasons a subject would be asked not to participate\n> (e.g., certain medical conditions). \n:::\n\n. . .\n\nFor the Dengue Fever paper, \n\n::: {.small}\n::: {.incremental}\n1.  From what population was the sample drawn?\n\n2.  For an observation to be included in the dataset, what inclusion criteria needed to be met?\n\n3.  How were the observations who satisfied the inclusion criteria sampled from the population?\n\n4.  Based on the inclusion criteria and sampling methods, to what population can the findings of the study be generalized?\n:::\n:::\n\n## Find Your Data Group!\n\nOnce you have found other students working on the same dataset, complete [the sample selection activity](https://atheobold.github.io/stat-313-website/activity/week-5-sample-selection.html).\n\n. . .\n\n::: small\n1.  What are the observations / rows in this dataset?\n\n2.  From what population was the sample drawn?\n\n3.  For an observation to be included in the dataset, what inclusion criteria needed to be met?\n\n4.  How were the observations who satisfied the inclusion criteria sampled from the population?\n\n5.  Based on the inclusion criteria and sampling methods, to what population can the findings of the study be generalized?\n:::\n\n# Midterm Project Work Time\n\n## Steps Before Wednesday\n\n::: {.midi}\n::: {.incremental}\n1.  Create a personal copy of the Midterm Project template on Posit Cloud. \n\n2. Insert the description of your dataset (from the Midterm Proposal) into the\n\"Introduction\" section of your project. \n\n3.  Insert the description of the variables (from the Midterm Proposal) into the\n\"Methods\" section of your project.\n\n4.  Pose a research question about your selected variables, **which can be addressed with multiple linear regression**.\n\n5.  Insert the code to create the required two visualizations.\n\n6.  Write a description of what you see in the visualizations.\n\n7.  Make a decision which model you believe is \"best.\"\n:::\n:::\n",
    "supporting": [
      "week5-day1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}