---
title: "Midterm Grade Check-in"
format: docx
---

Pull up your Canvas grades, we are going to check-in with your progress thus far in the course. Thus far we have had:

-   10 reading guides (out of 12 total)

-   10 concept quizzes (out of 12 total)

-   12 R tutorials (out of 14 total)

-   1 statistical critique (out of 2 total)

-   6 lab assignments (out of 7 total)

    </br>

+--------------------+------------------------------+-------------------------+-------------------------------------------------------------------------+---------------------------+
| **Concept Quizzes\ | **Reading Guides Completed** | **Tutorials Completed** | **Statistical Critiques & Lab Assignments *Marked Complete / Success*** | **Midterm Project Grade** |
| Completed**        |                              |                         |                                                                         |                           |
+====================+==============================+=========================+=========================================================================+===========================+
| </br>              |                              |                         |                                                                         |                           |
|                    |                              |                         |                                                                         |                           |
| </br>              |                              |                         |                                                                         |                           |
+--------------------+------------------------------+-------------------------+-------------------------------------------------------------------------+---------------------------+

</br>

Now, check these totals against the grade break down for this class, found in the [course syllabus](https://atheobold.github.io/stat-313-website/course-syllabus.html#sec-grades). Here is how these recipes are baked into a cake:

-   The "universe" of possible letter grades you can earn is determined from the Midterm Project and Final Project grades.

    -   If you earned a B on the Midterm Project, the "universe" of possible grades ranges from A- (if you earn an Excellent on the Final Project) to an F (if you don't do the final project).

    -   If you earned a C on the Midterm Project, the "universe" of possible grades ranges from B- (if you earn an Excellent on the Final Project) to an F (if you don't do the final project).

**Based on this "universe" of grades, the remainder of the coursework is incorporated as follows:**

-   If you had more labs completed than is required for your grade a + will be added to your grade.

-   If you have fewer labs completed than was required, I consider the maximum grade you could earn with the number of labs / critiques you completed. 

-   If you completed the number of preparatory assignments required for your grade, no change will be made to your grade.  

-   If you did not complete the number of preparatory assignments required for your grade, a - will be added to your grade.

**Based on the grade table and the process described above, what is the best grade you could earn in STAT 313?**

**What will you do over the next three weeks to ensure you earn you earn this grade?**
