---
title: "Your Title Goes Here! Make it fun!"
author: "Your Name Here!"
format: 
  html:
    code-tools: true
    embed-resources: true
editor: visual
execute: 
  echo: false
  message: false
  warning: false
---

```{r}
#| label: data

library(tidyverse)
library(moderndive)

# Reference the R package you data live inside, since you will need to load that package in!

```

## Introduction



## Methods


### Variables


### Visualizations

```{r}
#| label: scatterplot
#| fig-align: center
#| layout-nrow: 1

## Code to make your scatterplots goes here! 
## Don't forget to choose nice axis labels!


```

### Statistical Methods

<!-- What model did you choose and why? -->



## Results

```{r}
#| label: fit-linear-regression-model

## Code to fit your multiple linear regression model

## Code to get coefficient table from regression model

```

## Discussion

<!-- Model interpretations -->



## Conclusions

<!-- 1. Connecting findings back to original research question -->

<!-- 2. How does the study design influence what can / cannot be said about the relationships you found in your analysis? -->

<!-- 3. How does the study design influence what population you can / cannot infer your results onto? -->


