---
title: "STAT 313: Midterm Project Proposal"
subtitle: "Due February 5, 2023 by 5pm"
format: 
  html:
    table-of-contents: true
    toc-depth: 2
    number-sections: true
    number-depth: 2
editor: source
resources: 
  - "../dataset-publications/"
---

This week you will get started on your midterm project by selecting what dataset
you wish to analyze and writing an introduction about the dataset you chose.

# Pick a Dataset

I've compiled a list of datasets from a variety of contexts, all which are
relatively tidy and ready for analysis. Each of these datasets have sufficient 
numerical and categorical variables for you to use the dataset for **both** 
your Midterm Project **and** your Final Project! 

Each of these datasets are included in an R package, so there is no need for you
to download the dataset! All you will need to do is load in the necessary
package (e.g., `library(lterdatasampler)`) at the beginning of your analysis.

## From the **lterdatasampler** package:

-   [`and_vertebrates`](https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-and&identifier=4027&revision=16): Size data for Cutthroat trout and salamanders in different sections of forest (from Lab 3).
    * Additional information about the data: <https://lter.github.io/lterdatasampler/articles/and_vertebrates_vignette.html>
    * [Publication resulting from data collected](../dataset-publications/and-vertebrates-publication.pdf)
    
<!-- https://cpslo-my.sharepoint.com/:b:/g/personal/atheobol_calpoly_edu/ESAubSdYG9xNt8uEPfRMHFIBdM8bJigac_BysStGZI_XSg -->
    
-   [`hbr_maples`](https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-hbr.157.3): Data on the growth of Sugar Maple (Acer saccharum) seedlings in response to calcium addition.
    * Additional information about the data: <https://lter.github.io/lterdatasampler/articles/hbr_maples_vignette.html>
    * [Publication resulting from data collected](../dataset-publications/hbr-maples-publication.pdf)
    
<!-- https://cpslo-my.sharepoint.com/:b:/g/personal/atheobol_calpoly_edu/EQsqYRiS1g9JjNV6o3bRHKkB8V9wu26h6X1gzEv1VoOV4Q -->
  
-   [`nwt_pikas`](https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-nwt.268.1): Data on the stress of p
    * Additional information about data: <https://lter.github.io/lterdatasampler/articles/nwt_pikas_vignette.html>
    * [Publication resulting from data collected](../dataset-publications/nwt-pika-publication.PDF)
  
<!-- https://cpslo-my.sharepoint.com/:b:/g/personal/atheobol_calpoly_edu/ERDZ95KvsV9Js6I6JG0PU0UBPsFwBPKJ-h8FIIfTG2Wc_A -->

## From the **openintro** package:

-   [`births14`](https://www.icpsr.umich.edu/web/ICPSR/studies/36461): Data from US births from 2014 (similar to `ncbirths` dataset from Week 4).
    * [Publication resulting from data collected](../dataset-publications/births-14-report.pdf)
    
<!-- https://cpslo-my.sharepoint.com/:b:/g/personal/atheobol_calpoly_edu/Ec1AsfZG3YdPprEjMRfAAIYBi5zOAD3Pg2nuGhf6IIgU-Q -->

-   [`possum`](https://www.openintro.org/data/index.php?data=possum): Data representing possums in Australia and New Guinea 
    * [Publication resulting from data collected](../dataset-publications/possums-publication.pdf)
    
<!-- https://cpslo-my.sharepoint.com/:b:/g/personal/atheobol_calpoly_edu/EUxnosoiksNLhrGopLITu8oBSNoSuZGoNBJ9mdwPPeKJ4 -->

## From the **moderndive** package:

-   [`evals`](https://moderndive.github.io/moderndive/reference/evals.html): Data from end of semester student evaluations from University of Texas at Austin (discussed in ModernDive textbook)
    * [Publication resulting from data collected](../dataset-publications/evals-publication.pdf)

<!-- https://cpslo-my.sharepoint.com/:b:/g/personal/atheobol_calpoly_edu/EffyXD8fhLVPlpqdKiRvvCYBbtRMK9ihfbksjuMxWygbsQ -->

## Deliverable

For the **Midterm Project Proposal** assignment on Canvas, you are required to
state *at the beginning* of the document, the name of the dataset you have
chosen to use.

::: {.callout-warning}
# No need to download the data!

Every dataset is included in an R package, so there is no need to download the 
raw data file!
:::

# Write an Introduction

**Step 1:** Describe the context of your dataset in your own words! How were the
data collected? Was there a study these data came from? Were these data included
in any publications?

::: callout-tip
# Getting information about your dataset

There are at least two resource files / websites linked for each dataset. Please
read through these resources when writing your Introduction. 
:::

**Step 2:** Choose your variables

We will using a linear regression to analyze the data you chose. Thus, there are
some stipulations for the variables you can choose. You **must** choose

-   one numeric variable for the response variable
-   one numeric variable for the explanatory variable
-   one categorical variable for the explanatory variable

::: callout-note
# Write-up

Describe each variable you chose for your analysis---how was the variable
measured? What unit was the variable measured in? What types of values does the
variable take on? e.g., what are the different levels / values of the 
categorical variable?

:::

# Submitting on Canvas

For the **Midterm Project Proposal** assignment on Canvas, your proposal is
required to consist of **both** components (chosen dataset and introduction).

You are allowed to use any text editing software to make your proposal (e.g., 
Word, Pages, Google Docs), but your submission **must be a PDF**. If you are
unsure how to save your file as a PDF, I recommend using Google!
